<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns="http://schemas.microsoft.com/wix/2006/wi"
                xmlns:wix="http://schemas.microsoft.com/wix/2006/wi"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:key name="ServiceMonitor.exe"
           match="//wix:Component[wix:File/@Source = '$(var.MediaPortal.ServiceMonitor.TargetDir)\MP2-ServiceMonitor.exe']"
           use="@Id"/>

  <xsl:template match="node()|@*">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="wix:Wix">
    <Wix>
      <xsl:comment>This file was generated by the XSLT stylesheet 'ServiceMonitor.Heat.xslt'</xsl:comment>
      <xsl:apply-templates/>
    </Wix>
  </xsl:template>

  <!-- remove application executable from harvested file -->
  <xsl:template match="wix:Component[@Id = key('ServiceMonitor.exe', @Id)/@Id]"/>
  <xsl:template match="wix:ComponentRef[@Id = key('ServiceMonitor.exe', @Id)/@Id]"/>
</xsl:stylesheet>