//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MergeMSI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MergeMSI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; Windows Installer utility to report the language and codepage for a package
        ///&apos; For use with Windows Scripting Host, CScript.exe or WScript.exe
        ///&apos; Copyright (c) Microsoft Corporation. All rights reserved.
        ///&apos; Demonstrates the access of language and codepage values                 
        ///&apos;
        ///&apos; Team MediaPortal note:
        ///&apos; Only modification is to comment the messagebox at the of the process. (around line 71)
        ///Option Explicit
        ///
        ///Const msiOpenDatabaseModeReadOnly     = 0
        ///Const msiOpenDatabaseModeTransact     = 1
        ///Const [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WiLangId {
            get {
                return ResourceManager.GetString("WiLangId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; Windows Installer utility to add a transform or nested database as a substorage
        ///&apos; For use with Windows Scripting Host, CScript.exe or WScript.exe
        ///&apos; Copyright (c) Microsoft Corporation. All rights reserved.
        ///&apos; Demonstrates the use of the database _Storages table
        ///&apos;
        ///Option Explicit
        ///
        ///Const msiOpenDatabaseModeReadOnly     = 0
        ///Const msiOpenDatabaseModeTransact     = 1
        ///Const msiOpenDatabaseModeCreate       = 3
        ///
        ///Const msiViewModifyInsert         = 1
        ///Const msiViewModifyUpdate         = 2
        ///Const msiViewM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WiSubStg {
            get {
                return ResourceManager.GetString("WiSubStg", resourceCulture);
            }
        }
    }
}
