-- This script creates the MediaLibrary schema. DO NOT MODIFY!
-- Albert, 2009-09-17

CREATE TABLE SHARES (
  SHARE_ID %STRING_FIXED(36)% NOT NULL PRIMARY KEY,
  NAME %STRING(2000)% NOT NULL,
  SYSTEM_NAME %STRING(100)% NOT NULL,
  MEDIAPROVIDER_ID %STRING_FIXED(36)% NOT NULL,
  MEDIAPROVIDER_PATH %STRING(2000)% NOT NULL,
  IS_ONLINE %BOOLEAN%
);
  
CREATE TABLE SHARES_CATEGORIES (
  SHARE_ID %STRING_FIXED(36)% NOT NULL,
  CATEGORYNAME %STRING(100)% NOT NULL,

  CONSTRAINT SHARESCATEGORIES_PK PRIMARY KEY (SHARE_ID, CATEGORYNAME),
  CONSTRAINT SHARESCATEGORIES_SHARE_FK FOREIGN KEY (SHARE_ID) REFERENCES SHARES (SHARE_ID) ON DELETE CASCADE
);

CREATE TABLE SHARES_METADATAEXTRACTORS (
  SHARE_ID %STRING_FIXED(36)% NOT NULL,
  METADATAEXTRACTOR_ID %STRING_FIXED(36)% NOT NULL,

  CONSTRAINT SHARESMES_PK PRIMARY KEY (SHARE_ID, METADATAEXTRACTOR_ID),
  CONSTRAINT SHARESMES_SHARE_FK FOREIGN KEY (SHARE_ID) REFERENCES SHARES (SHARE_ID) ON DELETE CASCADE
);

-- Stores all managed MIAM instances. Each entry in this table has corresponding schema objects which
-- belong to its attributes and which store the related media item aspect instances
CREATE TABLE MEDIA_ITEM_ASPECT_METADATA (
  MIAM_ID %STRING_FIXED(36)% NOT NULL PRIMARY KEY,
  NAME %STRING(2000)% NOT NULL,
  MIAM_SERIALIZATION %STRING(8192)% NOT NULL
);

-- Contains the actual media item instances. Each of those media item instances have associated entries in
-- several media item aspect tables which describe their data.
CREATE TABLE MEDIA_ITEMS (
  MEDIA_ITEM_ID %BIGINT% NOT NULL PRIMARY KEY
);
