-- This script creates the MediaLibrary schema. DO NOT MODIFY!
-- Albert, 2009-09-17

CREATE TABLE SHARES (
  SHARE_ID CHAR(36) NOT NULL,
  NAME NVARCHAR(2000) NOT NULL,
  SYSTEM_NAME NVARCHAR(100) NOT NULL,
  MEDIAPROVIDER_ID CHAR(36) NOT NULL,
  MEDIAPROVIDER_PATH NVARCHAR(2000) NOT NULL,
  IS_ONLINE CHAR(1),

  CONSTRAINT SHARES_PK PRIMARY KEY (SHARE_ID)
);
  
CREATE TABLE SHARES_CATEGORIES (
  SHARE_ID CHAR(36),
  CATEGORYNAME NVARCHAR(100),

  CONSTRAINT SHARESCATEGORIES_PK PRIMARY KEY (SHARE_ID, CATEGORYNAME),
  CONSTRAINT SHARESCATEGORIES_SHARE_FK FOREIGN KEY (SHARE_ID) REFERENCES SHARES (SHARE_ID) ON DELETE CASCADE
);

CREATE TABLE SHARES_METADATAEXTRACTORS (
  SHARE_ID CHAR(36),
  METADATAEXTRACTOR_ID CHAR(36),

  CONSTRAINT SHARESMETADATAEXTRACTORS_PK PRIMARY KEY (SHARE_ID, METADATAEXTRACTOR_ID),
  CONSTRAINT SHARESMETADATAEXTRACTORS_SHARE_FK FOREIGN KEY (SHARE_ID) REFERENCES SHARES (SHARE_ID) ON DELETE CASCADE
);

-- Stores all managed MIAM instances. Each entry in this table has corresponding schema objects which
-- belong to its attributes and which store the related media item aspect instances
CREATE TABLE MEDIA_ITEM_ASPECT_METADATA (
  MIAM_ID CHAR(36),
  NAME NVARCHAR(2000),
  MIAM_SERIALIZATION NVARCHAR(16384),

  CONSTRAINT MEDIA_ITEM_ASPECT_METADATA_PK PRIMARY KEY (MIAM_ID)
);

-- Contains the actual media item instances. Each of those media item instances have associated entries in
-- several media item aspect tables which describe their data.
CREATE TABLE MEDIA_ITEMS (
  MEDIA_ITEM_ID BIGINT NOT NULL,

  CONSTRAINT MEDIA_ITEM_ID_PK PRIMARY KEY (MEDIA_ITEM_ID)
);
