// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MediaPortal.Plugins.MP2Extended.ResourceAccess.DAS.html.Settings.Pages
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MediaPortal.Plugins.MP2Extended.Utils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class SettingsTemplate : SettingsTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("<!DOCTYPE html>\r\n<html lang=en>\r\n<head>\r\n  <meta charset=utf-8>\r\n  <meta name=vie" +
                    "wport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\r\n  <title>" +
                    " ");
            
            #line 6 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\..\..\..\BasePages\Header.html"
            this.Write(this.ToStringHelper.ToStringWithCulture(title));
            
            #line default
            #line hidden
            this.Write(" - MP2Extended </title>\r\n\r\n  <link rel=\"stylesheet\" href=\"/MPExtended/StreamingSe" +
                    "rvice/stream/GetHtmlResource/base.css\">\r\n  <link rel=\"stylesheet\" href=\"/MPExten" +
                    "ded/StreamingService/stream/GetHtmlResource/jquery-ui.smoothness.min.css\">\r\n  <s" +
                    "cript src=\"/MPExtended/StreamingService/stream/GetHtmlResource/jquery-2.1.4.min." +
                    "js\"></script>\r\n  <script src=\"/MPExtended/StreamingService/stream/GetHtmlResourc" +
                    "e/jquery-ui-1.11.4.min.js\"></script>\r\n\r\n  <style>\r\n    * {\r\n      margin: 0;\r\n  " +
                    "    padding: 0;\r\n    }\r\n\r\n    html, code { font: 15px/22px arial, sans-serif; }\r" +
                    "\n\r\n    html {\r\n      background: #fff;\r\n      color: #222;\r\n      padding: 15px;" +
                    "\r\n    }\r\n\r\n    body {\r\n      margin: 7% auto 0;\r\n      max-width: 600px;\r\n      " +
                    "min-height: 180px;\r\n      padding: 30px 0 15px;\r\n    }\r\n\r\n    * > body {\r\n      " +
                    "background: url(\'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKoAAACqCAYAAAA9d" +
                    "tSCAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnV" +
                    "FPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkI" +
                    "aKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZ" +
                    "CFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdm" +
                    "CZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5A" +
                    "NgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4mbI8uSQ5R" +
                    "YFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHgg/P9eM4Ors7ONo62Dl8t6r8G/" +
                    "yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgugdfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2" +
                    "eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7iJIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0" +
                    "yLESWK5WCoU41EScY5EmozzMqUiiUKSKcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAA" +
                    "PK7b8HUKAgDgGiD4c93/+8//UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC" +
                    "/xgNoRCJMTCQhBCCmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRBy" +
                    "AgTYSHaiAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyGv" +
                    "EcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPEbDAuxsNCs" +
                    "TgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKggHCQ0EdoJNwkDhFHCJ" +
                    "yKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmxpFTSEtJG0m5SI+ksqZs0SBojk" +
                    "8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+IoUspqShnlEOU05QZlmDJBVaOaUt2ooVQRN" +
                    "Y9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgXaPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx" +
                    "4hnKBmbGAcYZxl3GK+YTKYZ04sZx1QwNzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV8" +
                    "1XLVI+pXlN9rkZVM1PjqQnUlqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC" +
                    "2MZs3gsIWsNq4Z1gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3" +
                    "hTvKeIpG6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acKp" +
                    "xZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsMzhg8xTVxb" +
                    "zwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZLTepN7ppSTbmmKaY7T" +
                    "DtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnutrxuhVo5WaVYVVpds0atna0l1" +
                    "rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFnYhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdW" +
                    "h1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPjthPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbx" +
                    "t3IveRKdPVxXeF60vWdm7Obwu2o26/uNu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ" +
                    "7XnIy9jL5FXrdewt6V3qvdh7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCng" +
                    "CUBZwOJgUGBWwL7+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0" +
                    "Adh5mGLw34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8YuZ" +
                    "lnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhOOJTwQRAqq" +
                    "BaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCepkLxMDUzdmzqeFpp2I" +
                    "G0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQrAVZLQq2QqboVFoo1yoHsmdlV" +
                    "2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0dWOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2K" +
                    "m3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWFfevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3" +
                    "HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebeLZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/P" +
                    "Li8ZafJzs07P1SkVPRU+lQ27tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jq" +
                    "un4lvttXa1ObXHtxwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3" +
                    "/ceDTradox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLTk" +
                    "2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86X23qdOo8/" +
                    "pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/XfFt1+cif9zsu72Xcn7" +
                    "q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9DBY+Zj8uGDYbrnjg+OTniP3L96" +
                    "fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl/erA6xmv28bCxh6+yXgzMV70VvvtwXfcd" +
                    "x3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz/GMzLdsAAAAgY0hSTQAAeiUAAICDAAD5/wAAgOkAA" +
                    "HUwAADqYAAAOpgAABdvkl/FRgAATEFJREFUeNrsvXmYXGd5J/p7v1PVXb2oJUuWbC3eLYPBCzZgiFlC2" +
                    "CGsgUx8E7bgZLgPJPDMk4chlwkwM9yE4DsQh0sgk4BzPXEGxoTYecgw45nMEgZswBNMbOwYbIxtsGVL1" +
                    "tbqVnd11fne+8f5lvf9zneqqtUttWR09BxVdS2nqs75fe/yezfCyjca4f6w953cTqyNl/Ecj/i+VQdLD" +
                    "owk9tzfJ4H50wFcHvH+skFLR/DaFIwmuU0fz7335PbkBKm/tQKcNvn7iEBLywCpBJsHYeHu+70Qj1NmP" +
                    "6n6n5yqPwWhTfYy81gTaLNbaxlSNAWo3FvivkkAfBKoT36gpsArBUD93k/+TgE7EKytEUGaSs2W2NvJ/" +
                    "SIjaemk+n/Sq30rbiUgew6k/eR+P5G2Ax2u1hBVLyWpBOiYA+WYuO//bonX5uzXk9uTD6gpSK0AZc/tS" +
                    "2739417nhIJmwVrawR17yVkW4B0HEDH3fpdgrYlAGsaWIGT25PL05f2qJeYS2LvAlh0tx5THripGVED6" +
                    "zCJKkEqAdoBMOF2/3eHTGtDa3LT89vt1iWGaH1RFOtAGCeqDkf+0A6m1ePVY9VdjV//PBmjvnp4nPx/1" +
                    "S2pY2Y+i4z6BCZxUK6+xVVnHcILNs2Jw5C4IVB2mVH+FFL6LIHFV66/hbBoDX77njOYQCCqdhjDhgyoI" +
                    "PjHTTgHBsbAHZdAZPS5JXEc/+HM4TF/HJjwX/jOLN5L4pcYAhgEMpR8FrC4sPgEw5QHZg9+//Ef3fu12" +
                    "ccf+qED6CKABbe33d9NmrYGVmoAqLctvd3ppeYEgMl0LyY3PW9iYvoNnZbdXlBJGkxUA14AmbuYJICmL" +
                    "itVJ0M+7o/B1akSODUawOInGUNgDtfIvY7BYs0yM8CMf33RHly1Y9+aian5soXnfeMikDEoTAW8oihQF" +
                    "IVbtARjChABhSn0eSY48EWwShBRWMwNz7vzYIwJ59Q/nl5HL3yqc8v6WOI1T3Rb8z/ZO3fr/d/+2y/0F" +
                    "g7tATAP4LDYPYh7wlyosQKtBrtUgnRMgHQKwLTbp4rx9RdPTq57z8RYuYmot8xLQnHNuNXOFGSOk5aoP" +
                    "R5AJaVccpI8KD34w+sDsD1IGWQM2PLyGeijuVFczWSM/l7utxERLFsUVESguHMRwSUPKSVsPBd+8YbzT" +
                    "BTOFxGDYCrJGR4jtTMDxphEk0Vgb+6UU5u3T7zs/Ne89sX3PXrglnu/8dXPJf4LZWguafdCy/q4pd69B" +
                    "Ok6ADMA1o9Nn/au9TNTH+60+5vSiyzVTk6a5n6Q/5qs1CyFC+BRy+qEyY/h+tX2x0t8QxJmA3M8N/njr" +
                    "AVOCYb8V+EAHiKqpJ0wgRisgBO+fjivnAWrf7w6LuJ5pnThs1vIdYEACKAn1zR97XSLi8vOXP/qF73hL" +
                    "X8yPr3hDIejaaeVO8K/yfo1ZgBP2hY26aQ76DpQsamzfvvvzEzgpQYlmDlc7BoZxpnHCIn6r5voQTLkr" +
                    "PdMYJYT+16pIHWCteQkCWYaZDweey/Fn1fSYlR99/DPUPjucWHLk63BykHlQAFSCosUrFEjSWnKCqw5I" +
                    "KfA3TpRnvqSV772M5vOuvBZTvBNOUE4LtijIr3SJqN0ikTtK6B21m35wFR76emcRVGOt+XaiQhan+sSz" +
                    "Bj9Q5n1Sfb/FEo5XQjxBJKhsIRIfW4ursJBDa7p7ixwEMH6hSvsaA7nRYCLrVDrUOeITGVrGmOq3dmoX" +
                    "PfllGTNPQcki0L4Bd4M8KZAXgITZlq98SuvuPxfTZ+641wH1EkH1rEkeBSkqklAahKgdoQDNTU2tfkdE" +
                    "+3+04JKANekpHdymnCqT2ICViExWMlJbjQlwq3/TUKKExkpDGAtYK0Vh6mbEceHSNVA4AjdsBDdugqq2" +
                    "5BB1PyJiSRs11TTcEShPifeDFDAg/IrcmaAtXlbNgXtVFEWVz7/ef+mNT65Saj/cUFvmlT1NxH7yokyY" +
                    "+ueMdExr1CSMQEjc7MNOpgFoFQYNiSHsZYClLMhSJkOlfp0Kp7ZUSrkLnIUp/5vOg4QGzHFStJbZwoE0" +
                    "ARzwL1aOoXCJArnwJ9BLxhRMQQKtE6rKRMiYWuICGxZmQhxR41N8fZ1KoU3dmjysp999b9IgJqTqspGl" +
                    "U5Uzdsfn5j8p4bLmspk/8+fRJBS1/JkKXuSKPzQYU5WuC+kr/aEtQQJVoF73FoLa0tx8llJdOao0Y4Hz" +
                    "19YIgCxouYsO0CysECZKxBTNIUCdSeA4YEstUzKGFDw4Flpv8BlIzp4XuqmXr80A1J7NqWyzl5PF2/Yf" +
                    "t4liZ3aGqb6ZZg0OFNFZ8Pzx4v+ZlbGYF2N12xLqgnEKBVTwZwwBdzkcbH0/nIOl1sQ1pkmgvOLUjaj9" +
                    "j3Y+XgyAbykt5FDEs6WtdaR93GReUfJS1FmK0whUhrL89RZc0BekhqINVi9wJHANMbzrEbZrVL4+Mcuv" +
                    "PRZ7xae/1gmqjmSRO20xzq/4FdpTsUrm1MtK7EkalKRs1ZEnT1gdUzyVyVLQLvDepA6sWTFxfPSn7024" +
                    "Kj2w9pac2cK4sukp819Z/kWJ2HZ2ki5Cds9cNJgvfBZn3Ftz0bASTNAMwLanq3MBqPMgDRQ40Erpeu2K" +
                    "T5j/Wln7cxI1EJK1CYbtQ1gjIqxzWOmf9qwgG8NaELUN79JqjAZyhTXiMWDcllkqC+pXsDS0ULlSQX1x" +
                    "zGYgEivSWmy5pLU2c3WWreYLKwHKVv1WyWdxcJZDOfFsqIRpTmgggREWbDWmATSlJ+X1HVaSyMkJ1UBo" +
                    "CDgrAsu+sVMnshQrz+YAMXY9AtJZWEl3GUCGBYkdTD2OXWCMj+E4woDUZIdQ3VAo26jKdrEmLhIKoNJR" +
                    "agCpWNZq9g1hurhEnjdxkdx0cxhFMTaLve/0/sBgWeVgRL9EziEpyn87tR2VY5WstA5+BOcCRr462tD6" +
                    "JYbqMUcEyAfO/WU6YsyjpTX8iGEShn13wLQLori6UAZwJlCTFNRnIRDUbM7lQrJUk6U2vvR6ZIupfTq0" +
                    "zizkJwhuULSVhypNfn/WVNLaKO/pkBd6DEWf7wH547vwbM3tNDtTOPhcj0eKDdg31KnZg5wJXarTBEYu" +
                    "XrjWXaAM8KpMkUMSquol5SyLOxaEvkVCbMCEZY2MtHIhV5Trz+3TY3RdMY+DRq/hXztU8jeJ6KNKVGvE" +
                    "evsI6JEZXOdotIIF4eJqidFOQMwtXBWlNIkIjaJPx+9eeaKmnTSySZS5+L1C3j+hgMo5ubRPWzWnpoig" +
                    "C2wcLiPKXsAV0wewEvW/xjznQ34Xwe34d5D0+hzAbYWpQOYsQAMKw/bnxG/SFlmmHF1JsgUQcCwreg7e" +
                    "U5Nmi5GMtQcJbKT8xok3MDsCMFijEFZlugUVEyesuXUw/t378vlAbQaElIkYMfr2R7JfSn5JHEvVlJ8f" +
                    "YJSR8GQTjsJYCWdmeIkgIXKvArUl1BhlgOl4h0OJZCZ8fId83jx5r2w80s4cBg4ZKuLuabanytwmCorE" +
                    "S0DFAZoo8RZxV5cvGMvumYCtx7ahq8+ejoWbJWUwlTZ4UwAwzjgWZEiycrJClKO9XmCB6vL1LLMAawkN" +
                    "KMJ9qmJi8No7ViZBCYGK1RCkU4YIi4xPr1+4+H9u2VliJKoyGRQGRH9NjVDn4RDk3ygV7M+lUzSTgqIM" +
                    "jkkY3qHLKokpGpF/Nt/RiS0WXimJvKQHN8LEF5z5iG8cPNB7Bg7jIOHgYOgIyziPTqbceBsCaAWpnI6C" +
                    "gK2jC/g/1j3Q7zy9F34293b8J8f24LZXjukM1owjGMASJ4za0FFIc4hAlhlVpXkVqNMYZ3rKoISPg/WL" +
                    "xiTpnNykDAxwQYx6dQ/Nj65bh0aKphzaX4JYDkkcwagJWBVCQ7uOYDr9qi6r5VF3v6NnnlKgXkzwXIVP" +
                    "gSxU10G5LziSoX6ZGfG5ZsXcfVT9uEp0/NYWAIOLQhwHEch1CpX2okUCVTjJK17ftv4YVx97v147Y5d+" +
                    "NyPzsfXHtsQVDy7sCr7aBGopn08iIugaqha2GQ09SjMsiCAnJIzDbyq0qbSDBDArGEHnMucolT1N5kA+" +
                    "ayijBpJTVeYOvKqH6Jf718asoUETRJUhYHyPCmcc3KEuFvVjoaSKXzbpkv8X8/cjSs2z6PfZxzuai6YM" +
                    "it1TSWqU/2FqQPVg9U4IWUI2D4xj3910T/grjM34hP/+BT8+HAHQJWvihIAikraOmAai1gVgEq9F4L/R" +
                    "GL9SIFjUm6UGqKIJg3HSGETeVvP/YoLkitXopznkO1ukkq81EBmGYuEplTiFxX0vcgK8gm4MlavAgMEH" +
                    "TVSUSQbVDzrIDPWjVm855IDuPFVD+OF2+YqusdJqZT35jSCtoZkf5GqexNBG0BKdS1wycw+fOqZ38Evn" +
                    "rUL1vqgRoxi1RLEBfVl0yy1DFhNSOLWAQJW9BNqQQAhMRsCRqiXZST4a420xFPVnwJXZteDg5fOMv7sw" +
                    "ZZk8kSpGu3MLI0VPDYOtTxV1KnKRAcb589Xr37mlkX838/djfNmurAM9Mt4nNQAOt5KZEmAs7JTOYDWA" +
                    "9U0JPFsaHXx7nPvxdNnZnHNPTuxUFa2oCECG0fbmQKWXYY/x4iVZQ5KsEoFlG6QswpkLoWgvOTJ8+FTC" +
                    "PM0Jn87f8FmMDZIyzRIUjRdt0EdryQvl5K+KlJNEdRpEkvkXG0ErA/fsgCx5eAU+HQ3MDDZsvjQFXvxh" +
                    "Vf8BDs3dLPnwnIikUhmLK0xSJFX90r1C43gTQBKAjE/e+qj+LdX/D0umJkPgYIQkOEYqeLk5FhxvWSFQ" +
                    "T0RKAlvM2qhb/k4JckrsebKaOug4TKMRBrW85spyS9NkC3pKVCSW6rVCQuvXUegjMi+pxBShLOpLLhy6" +
                    "P0OxpXbFvDln38Ev3rhvqDmcz9bahmT5AgfD3mp/jsVBihaGqSUUf1NX3lHZw4fv/S7eNW23SqK6EOtC" +
                    "qzOOTYyjOw9f5HJL6t6lQZMol+cybLS0SgNVgXYjMBsjbrKa664ilhES1vbsiJRRNT2aBuClQFP4KCWI" +
                    "i/AYJ9MLFcqxWX4Ty6Yw+8+dzdaJgKUdF5HsPGS2EFwSo4HkeodSyVFi+hEebBSg/eX/oT1rS5+a+f3A" +
                    "CLcsus0FJ6+crwrnIqPAokDV11xoA6O1lZGXSHMNi9gTN2HkUWZaS5AcL7ZZmuucttwoBI1uFOCaeV8V" +
                    "o4Mu0kXnx2ImLwXb1RCi498EEXvPtD5nAQNAHzwOfvx60/bV49z+yQtkRXlwWs8uZ5qBMbaE/4ClAUBL" +
                    "arbp8bZjKN8VwPG+8+/Ey1zCb76yGkwpoC1jMJUzABZAybrXgm0HCVQlU6TAljZL1G0isDgRMFTXelsJ" +
                    "Ev8NgtOggIqPrkCoLIkGQX36Ul9GfFkfdUZDGICE9dyAqrAAETdvgiBiuNYmSCslh9jvMX49M/twcvPm" +
                    "Bv49ZNob5BGhgaYL2tJTRmgVbhb70il1BQNlqy57b3n3IVxY3HTj7fCmMKRJhZsCLa0MEUVKKmiUaTpA" +
                    "de8I+QAiOYTIYnFaHZc92CI1CJT6svwCIttVH2U5IAqmkLCMBG8aV2VyrVSKaqVBy+Uu3DEfOqgDZ97S" +
                    "qePP3nJ7oEgRerRJ6s7reqm40T1e0qq1cCh1kA64iIriPHrZ92DF5y2F5YdXSWy29hG2xWB1opqWlbCR" +
                    "qqLM5qUaglyVqRSSjNguPs+KlBJZ3sQ0kzw5P/aZzdk4Td5j4IKkcklRIEjwETL4rMvfgIv2j4/mtVSz" +
                    "0yrg5O0s7CWXr93lIxp5lBrC2/ErU0Wv7PzDuxcdwilLV3OK4sUwpj26M9/WdqYFpk4WjL7X5KvUbaRc" +
                    "qg4YQNGRaoZaYlrvwi11HzFieaSOpIOJ0JiyvKWEDsWGU6Vwc4V7+ZO5Kdf9AR+5rTDw8nzTPdNynCnt" +
                    "d6Ya5zhLzlUH98vUpB6XpOFrTribsD48FPvxOkTXdiyHygrb9dbkSIY+k4JBkDSVfEaOu1qjEq8ToMDw" +
                    "RQgSsrcaZVUPyBq6nXjsKy05NSYTkKiolQyZK67bx5q0DikQwQH6xMv2IuXnjG/fH2atosVEpWIU8tmT" +
                    "bcYkeLg8RdUl6oriVKcPjaP3zzvBzDEYFtW4BTBFMsszAPU8n1JsD9p1zCuYSWNeslEbJ1TsDKg5kzet" +
                    "MEY6pniqWTljIjPSVltRHp6ivGWC+fx5vMPjaxC0yB+CkRl7x0nICXSkSlln4rvrCJTRxisuGL9Lrz1r" +
                    "IdjmNXxq9ap+PgYaxuVWXRGqVcE5wNDHCnKJDo5Sl+FkW1UQs6Gowb3WtSP1/CaVplGO1RGSmxVFxzU0" +
                    "kvOWMBHn7NneWrUChUp6ShHj8lQ5PEUQpXOVIu03UoATOqPrsDM+MXTf4CzpxaqOixblZQQ60YSCLkYL" +
                    "BLWdQOMPFilAKPQ2C2taWsMdS7PRo2EQ1DXooVh/DH6g0JZic6A0I3IVHkyi/p8q/jTdWMW/+LZ+1HQy" +
                    "qWVz+8liiaG9BmPB8maStJWoT1+0OotrDZZ/NZ5d6FDfXdJfBFhLIb0Ws5a2btBh6VlQwzJ4udZgTqbR" +
                    "EPU2giqP+U/uMEMSEsfNfUUaulV1xNWCyD8eCuqQxl4/zNnsXP90pG50EmNSi586vM7VWxjjXbiCpitg" +
                    "nWan7BRiVZXDVwwuQ8vO30PGAxbCnrKWuiOS4LpUZ0GE4rSh72tiBISZR0q/7dM5j5y1Z9R3vpkJbYKQ" +
                    "5RMcwbglDQEi3HoioaqmH4G47wNPfzKBbMr43ugQ6VSCqS5nceF+qcoQYM0FY6Uyp5ape2Xtt6HDe2lY" +
                    "Kf6lj1gq7rORPOM8/0cZMK0oqtEyTbHlpnaDODVcaa06K7bF+F7KeHa3EmFhdgLWTsWACwsgDYxPvrc/" +
                    "RgzvCIJFW4Rw6mG0t4Bx4lDJUKmMhIViohSkB4BPZXbT20dxhu3PhKui7clgx2KKEElNSUb/KaZWECS0" +
                    "ES6EYny9HlVeFRSwGMV5yT1hUj0uifS6p5VFxDK2q4sukG/5MwuXrhtYdUiPlLlS4GbJlKvNeFfhPBpc" +
                    "2RqNe1Uv/3cxh9juuhFle2viI0pglYkkmr3wmo7U5SxWy81ZSYdUc0J5xXzqFlONuXVktAOCdszCVnWm" +
                    "vjIrmCC73zbhXOrHp+sFYWR3gUjtmY2akECpKIi1f99tHJnN7fn8ZqtuwKwVC6xCMqEzjI+qm+8Vw/VY" +
                    "UU51kmzC+XOODNvFWzUVEUmZbHQ3n4u8x+i3MTKX87Sf4npfi89o4sXbVtYNQAYAVTmujQyOpCyxl4/x" +
                    "cyppAKVsDqqvmn/+VMfxGRRBrI/ZuU7z1/Qh8w2BHGIqNbrVpL8IewqqjPUY0ne8hFKVE48eM4S9rV2L" +
                    "1nmVB+r9hnu5Pzq0+ZWRY2qW9KqX0pSpRmOA0eqRlGZY5OLsLk9j3Om50VDOQTC39uqtSuZpFbW/G/Z7" +
                    "1UwABAt9XVL9yO1UTkvPVPBKWO+9RfkU+1jm5348Ppxi0tPXTq6eEjsPMLxMWyCED39tMjvWK2hKzbsF" +
                    "T2ErTMFxLAP3zNApHFxYirUABxs2eg4R++bVXHhEat+lZaYGwJR+0KctRwo+UFSIkt6+Hlbl7BpvFxVl" +
                    "eZYlphALb5btmBuDXcD5/n7BGpvp/LRVft+v3LmUbTIhq6CISJlpf8Tw6tBTHFGB6dCLs2WS0paVqT6q" +
                    "ZZLCtHGsPkN9WhDfhKHbDYLZrz0zMWjI0EziytSfnxceP61OD8l3v4x2LaPz+KcqTlHP/mOfhwYgOgAc" +
                    "1JPx6qb4yDJmoQxoQuvj1D1j5I3mAPt0FqYTMFgqwCevXlpVevkUymUpvZBMABrbqOylqQFiUb2x0qiM" +
                    "+PidQejQLIcyptjy/bYH5WFto3Ne1mZBkpAxfbYSRLLikKoOaTqUoM0NYm5Caz1Dn/xfvWDN45bnD5ZH" +
                    "lUsSOkUVKs5vjqltAqgbYB2Kxb0HcvtzMl5x5ly0hfPt0qyes5UIngis0JKA/vxTLItE9vh13tkHpUzY" +
                    "FUpeZxp+ThAlMtMKRkImGwzxgtebSHVCFZP+Bs6Poh/QgVQX30qQ7zHctvY7iJOj2FRnkLKLrVWD8TTw" +
                    "QJ/jvX8hCq3IuHdh6jf1mgXWXQ5zhl7mb6mkDNNRQRAdZWWKTjuhWOmUnWr5nwLdU+sHaaQ3wl9fy0df" +
                    "2+CtPxuNPd7rLZTikUQi9FGuoVIqO41puJUW4UR3QChJGfFtxohWf3l93mYRvspR6r6eYgtmokIJBNIh" +
                    "JSldJ6JLlMpV3swSUMkh0gnpZhjTAENJPyLSuV7mmotTJJTigV0Wn0lkNjTJ4lN6UuqVS8rq5NTfE/bO" +
                    "i5GNIeOSEhxgzstJ5MgP4hCl1SnVWqExT6hb4+Kj6K+pgyZyjS640X1tw3QLtauMcaUWcJ00Y/TY0Au/" +
                    "bI+p0sLNHLjLElXfmRGzwfgujwBWk2gpqXMac1BzYej+ngekc4YcepAO7sEzHbN0YmjQzduMIgcZctUO" +
                    "aBHszH6SCQFOYlaxOz+2vT6Y7C3qcR00UdoCBX+Cx3vYpFebARa6/DnzcU4PFl79xz6Q/BqS1TOOFWD5" +
                    "AM0dJPZMknPCsz2DO490D5qHGW6S9XvJdmqBhrE3lghm9BpnRZX0tTkMyqPifkBxmTLOikKFe6UlBRDJ" +
                    "654u1O2koz2J+Wd7WRy9hEBlTPzouJAsbyXL7uRKBuAkhaSHrMk6mpAuOXHnaMS7ZH3fSTKJ3745I9FO" +
                    "7Z60rOp9WHTvFf397ijptY6StYmG+cmiO8im0fUk0lk7b7r8S+calUUKOuwmAdKVXOkwpSo1rI36HlCX" +
                    "ee7vm1KPBDnr+NXH5rAod7qKOGciSclqU/4aBfALjuFQ/326gBU5uCy5rcVHpLHegxMtjnap2u9ZSbOh" +
                    "Ho20WA5bYLHCT+u52VJ/jzpbrI6qp9Vdl6gGtKVhFzrHqoXehEgR1d6VD02X+Dbu8ePiqMigyOhGVkBd" +
                    "LmFT/1g44rtTwwpRrBc39VrCsbEWPT213LrWRNWkdKS0lxNBtoh11xCjG3XdCXUKNKVVaGiIboka2GUn" +
                    "8SiWaytNT2Tvagy/SBArr3kR//3DOaWVtmpgiiPZjd1y0Wm/urRjXhsoYCbf7M8+9OKPfOcteK26X0W6" +
                    "FnAjFm0i1jiTYKzPJZqv7QGh8pWTWfWS0ZISVNOwQvoiTVJIIgwWmOFZSWl5EKllEpQzgcaYhEXQkeU+" +
                    "jiCaLP+4/4W/ujumVWVpimp7is8/9ueDfjCAxMjOy5SvacDqb3UVCpdSM/Sip31fqAAOmORNss1eDlW2" +
                    "wK3MNtrR168DlnRdjRNWIorzA+zkPDR/gyP9ONGKpdmNFNQSrtn4ll1AzmdVJygw8TXfebuKdz6WGdVJ" +
                    "KksgpNRqAfmJ/B7352JhWYDDPpB6j2ocbeXDPQFIPuswdlP7h8kYGwCGHPSlJfLIqzyvq8/iYPCXmdlO" +
                    "iWTwkW1qeyZymlln7JdqR5MWDE9xRqRcixkrm97+r8mNXL9vOWAiVgYuFgS3vE/NuLu/WOrIk0padl43" +
                    "6EO3nXrlsoWa6DUVJJP4vh4YHo70woAWgfCnlPpfRuB27cVcHvudq4F8AQwMSaSY2h4g+GjKWGf6E+i9" +
                    "M1HbApOEmS9TIbSTe+MMbUez4rSkobrynnU3NmhrEqtVf9z7O4XvENht1IiYTWvVj1zsGfwa3+3EXfuO" +
                    "3LnKleBev9cB+//35uxtyttpNjhmm3FdYoB1GG3wt70961Q6X0L9Mpq77vbXh9YKoFuH1jqV3+XBuhNA" +
                    "MWkAynVQZo90cdge2KpE7L6ybU4jxIxMe9q+aXVTexhFXMFvBNmVSgWq9TNT3YRIuRlaANnmLNBSKY4S" +
                    "IbC9T2C61QNqgZK/OhQC7/4X0/FzQ9OHXltv5BK39k3iXf83Wb8YH+hylBMJhiR2p5eUsr7fSE1PVCXP" +
                    "EAt0C0dSMVO48DERqAzCXRaFXeq+mBxppAPeVPgaKj+Hxxep3wThpxFC5X0FLShkKz1WQ3italdO0Lg3" +
                    "yxPebIesNY0bI3Si8yJ6CekDWONnxpN7msZAsG4v4GDSwb/59c34lf/12Y8OHdkXKdl4PP3nYJ/8t+24" +
                    "LGFIpT5pjVdqe2ZqncJUAlSD8puPwFmH1gogcU+sGSBmVOBjVuAsXbF34YoVBoQGcAFH01B2+UWvrn/F" +
                    "NW5waTturne51QNuEMGrMLYJdlaZ4QEi9Zy9CcPYhFI2JpOGjJIDdFiZtWz388CYHESqqBATAUzHDsVE" +
                    "wj/6eEOvv3YFrz6rEX8/BkL+JnNC0PzV/d2W/iPj0zjpgcncfueMV1/njRGkJ56061NnCfvFNnEk2fnQ" +
                    "FlUtxMd4PQtwOSkG1ImWkZSU2BlDbT/HfOn4fHuOExBYa4qxPBdRhQufmx6rc2XhZvdADXP1o94r/2Yl" +
                    "eajIok6+QkYWgJ5VS3+TixPGVJlkt4eEqOcY/2MMIhCyI4J+3oFbrhvEjfcN4nz1ls8e3MXl2zs4cypH" +
                    "iaKSmceXCrw4KEWvrNvHN/eM44nFo0egSidzjClxUlNWweoJOe99y7vl86W9d59X9BRfQY2zgDn7IhDP" +
                    "Q0AS7oX1hqF9Wvbf9m3PYBPXsdqbRs5GbUalFyI7iimiG1+kEjWxC/3I5Z4hNTO0SWqaHWSNski3TdYS" +
                    "+AaWPWI7Nhj0ydmC3xy5PDCGCCK4GYAD8y28MBsgf/wACXdWKBKZZQXLRK3SVwFf9dLQQ+gMic9c3STU" +
                    "/+SfgKAc7cDWzbl7S7G8dOXFQAO2XHcMbsuDkmTY1coApTIaBUu+44xqdJ5pnh9Q/M1hxarsMSrAVRkm" +
                    "/USSI02Vz3eJPWgDGj3PiKQYWGQQ3netR6snCyLIAlln3nUO04IY59Y/+3Vv1z50mGSUjO1T6Wd6qkoa" +
                    "bfOTAA7dwAz083XoPHy8NoA+MtPnItDvcKN8nHmkfHnLtbFeMXqQejPP1tWBR9AMlPMTZTmPOu+MqAyk" +
                    "ihSEhIl9RCLnvvpmc8PsyZKzADEHkdkxFIlPbKSxGMgEaojCipKzlsNrzcmmCpaChAsGD2rwSrJeanqP" +
                    "Q/q6SgJ1q2nABefe+SJ2GsB0l39dbjxsW0ifxSho0l1iggFUWWbkp895askjTbRyPkZLl3ACwM9ITyVr" +
                    "CsBKteJKjmJT5nRInTGYUwki+7TXO+a4iSn9YAPibaoSVZ2yjKqm9iziESVQLBFmYS36k6uJzrEOCAWL" +
                    "WdYePEepDKq1BdSs8+OK+XKy++7iY2XnAns2Dw6K5/pN7wm2427z8aiLVCIGK63SxmEQlQ5S4fZuHp/M" +
                    "qTBCNFhBVKjep7LCo51NWzU2izynB0qwUpqEEJlejYUBroZ8Ma1J6TkuAq80uMRTc0IRk85AQFuoURnT" +
                    "JgNBNFHiSLP6g7d7WtbU9qfUoJ6oPYsoWeBjdOMy88D1k+uXl7Csdq+Prcdf/3YFphWbGQWNI/xPoFjS" +
                    "QoSPnVc8BQGLXOIMsakpCTdj6MNzDz8l7eWfeaYRaJznRSgAW+uPS/sV/YhN8uV3cMUbZwAWIpBJNahW" +
                    "N2XlWpOWxgf5CkTD9OUlLaMxTLamRKQfQHWpZIUh7pzC+NZ5x95R8C1HHF5sBzH539ydlDlRCY2LTO6z" +
                    "MTboaaIRXohN1XkAwb4+vE/ThRX0tmnjkE5ViuUqGK6JSUSPT5TA2ujN6uzG2qvk+2DTFDTFJseMikbm" +
                    "CgJcamkU2hmgqoZn2mFt9TRloGFXozReyB2Sy9dCUs2Rp3aBfCipzK2bcIJu/3+Ty7Gg4sTaky58UkHb" +
                    "hZuZedbEBXRTzZS1sSyE4JRs6TCeQ4nPZZR61GVK/b6ExSSTpaoBQKY6zmGDVOqa0S3e53hGocAmWYYK" +
                    "S2vqliVuoRJ1KLKldz0ZG9CxGHDbjFS1fjrsIssLQmp6tV7zz3et8CODYzn7QRmJtfYuFzB9rk9T8Nt+" +
                    "9fDEKEwRgRkKrAGHtU5qBCAUxpO+BMhjdMNxGJJ6xABthwUdT9SoBK0f1/j+2WYCU2zpwKwoAd5cfoJD" +
                    "ngwUA6VZpuERA3qRk66phSjEeeezgrUSfUCnzNpS8b8kovPWwqSs2cjcAHgsu2MK3YeXxzosp2nfefj3" +
                    "/34dBQtitOijQmq3/8NF0EkSUnBKOYxJkZTbD7BKR5kb4cqxMdAZr7fip0pbrQ5a8a1t2WZsqD2dmi9o" +
                    "EljXky5AkJ340iXM2KzLkltkaOajM56CYku3ixgMUPAx/TnelTF6oUE9YCdbAOvuYixdeOJK0UB4OYDZ" +
                    "+P/ffAM19fKSU5vjyZteEAulArAkD/vXqJWt0bUPynGRwQYg1Mty1YQq0Ro5Tbq8sBKylbNAJIaqC5pH" +
                    "qiR6xSbc7GuKZCWbrCVXHzaIDmen/WZlEIwRT1UWmC+7yWqAKoFLtoiVP0JvN3wxE788cPbK+rTE53GV" +
                    "M4Uycidu0ZGhJ8DJeVpQaOuRSVIWAiSeG2iDiwDeoNZMISkai1LoNbdq6wFoAh7kVCCXO8qKY3TIDyk7" +
                    "jZC5buwjU1NCygSOdIfrA7FFA/BSYM3yxyA6kFKAK48uwLpibwdtm186tEL8JXHTw1NyogQgGhAos8+B" +
                    "+CCLZgKIQxCIDVeQNn0zjJgrHBaOc5wCOahDfLD8nDttGzCX3GjVHd3tF+UDOclZxIASXe3SFFR+FEc4" +
                    "8lpxgBFnpQoJpiF76TKzI0u74UGa7SlnOovgfmec6ZKYH0HeMPFjO0nuKp/eGkaH3voqfiHgxOoMEcVq" +
                    "yIGQBDJNpEIGqxyqqQ/lLwGMhMuWlqkMpFifwhJ1Mgu1oPOb2vZv1jRl6Qk53KkcypcZdAqhE4VnSVAH" +
                    "d11mWslLBMv813uHSqKRUtPrgSyUD1wo7+7vUqSXraV8bNPAdZ1TmxJ+rVDp+Ff3ncuFmwLxhgY5wjBe" +
                    "LC6ETyhuV3szy9zLQh6YVf9pdLmN7IilXXFXQByDGun1371gKqiEXq0YJ06GhTrjsa4TLNirjtwrKa86" +
                    "c+o9QQKBLQPGnjSTmRhhchePHH+h/TLCsAvOpfxgp2jh0GPT1XfwqcfOQ9f3rUJZCpvnFz3DQNTOUDeg" +
                    "WJyHj6pAAmJPqa+nWTIm1D+ga3IfI6qPxiIzjeQF9h6wt/67n+rIVFF9Ej5U0Nz1KIHmDlcYu1m351Eb" +
                    "dK4vv4i4X/vCJD3OgnELpuAYnI3c62bEjZPAT/3FMbZp57YUvT7izP43QfOxb2HJpw3H6NNpBLVK37UG" +
                    "O3txiJICn6GIaPs/WgeCLtThE1971QlTTN2pWz+uyKvX9mODT4/Z8n7VHcPAnaNP8j/rIRaUjD1ZS6ZH" +
                    "jSy+yARYFXRUbW95exDePvTF6oCwBOZetq7Hdf8cAd6HpwiEx8GTrIaUToiooGBQxULn0kknJBiZ7Qg8" +
                    "tkTJjajiMGo0AjCclT9rDyqVVP9WgJGLGZ0fDbNjxqENYdkWzlNQ1cNuMWChNoKq1XbVP5xK78x2WAGI" +
                    "N5g01iJD1+0H2/cduCElqL7++P4+MPn4L/uXu/CoARDJoCPqPobbmRlaMIlyp99Wl/l1fuEobrskMFHZ" +
                    "i0ZvLmli/j0qNHSai9q1TL8eVBECjr6pO9rSoOgw20KeGlYTdiZJNCvknalES9fEwpzBDHtqCZLHJyoF" +
                    "25ZxL98+hM4f6p71KXo0czm/8ahzfjEj3bgoYWxEKsnXzFo9FCQUGSSJFkEK97lnHKQfNHmrwKAHCp2B" +
                    "9XncU2wRJMhuLPkZwKshkT1qE88v5h4kHiEJLP09fhgldySeELSxPDxUCU5Cfo1QWKScKxk/TlH588dK" +
                    "7yEgV8//xA+fOHuYybxjgZISyb8f4+fhT96cEuMLjmAGkQVb0i191BglQnnzFXKpUxO94ClQhD3Aciot" +
                    "XmyzK4QgGIAwM+rEpOqScwdi4GcIwRqmirY6MnXxeUgcgq6BJsEPZG0+0kkdnaIhvgoy2lVr/T+qzdtG" +
                    "rf45DOewIs3z53QtuhPlibxwR+ej+/NVg6TD2MaaA8+TH92lYRkjDiPMa+CJYft6/RZlpCwqO23wiaNs" +
                    "ZdgOlgCDCfD70i1eWLn/fv5t4MqUVtHorciNSQL/hpi9w2qvo7nTDWgUhoiugWdq6qbXDjPXpS+siuEY" +
                    "iK85LQF/Oun78XZk0s4kbe/2Xc6Pv3wNuzutqJU9Oqb1BTiWGvPHrT+WskZUJG+Y5H4LsPLnGQHVWMmY" +
                    "+MMFvVngAWsAZMViUVWg1UGZ9iu3OvPEkmikStRWtpHdWeJKEtH1er/kuCB9Dw93WRJsxBGJeBaWHacA" +
                    "MeW14YI7915EP/8gr0nNDfatQbXPnIO/sOuTcGbiQOIXVY+4rRm1ZBM5GVWgtQVVrrqisKH7HzI1Nuox" +
                    "LDWVjmqQlNB9kGligy1PorFDqzsJatxVJWmsLw0Bmilsf4o3rU3ECVg3YlCJPO9MwWREOIL6ZGXwOnHR" +
                    "BMByk72RWfWhWb9mjUkOnmAsbnD+Mzle3DlpsMntBS9e34aH/nRefjh4Y4eNEax3Xh4XPQ0Z3fxfMg0B" +
                    "DuEw1BNfa7OXaXVK97ZeCkpwCqlbLwWlFhhFCf1MWBD+R6pcCrb0UbgtI5A82M4VS8iSmJIlmi2oSRlr" +
                    "lVIOpzAetNbxJMr6VqR+WFFUpjSDQB41dYF/M6F+3D2ZO+Etkf//LHT8bld2zBbtqOzE5Kc5DB33c6Tw" +
                    "a7bjHYPYgtNFqmT5BwhAkoLKkwcgueL91hnd8RkNqvf7z7IO1ZgnZMc/A1fPs2DQ1Ot5SA0pahi1pNON" +
                    "AGnzlfdZGgY9Je8hoOzpXsxVUm3HqQsqwwsO48X+O0LZ/Eb5+0/oaXogX4LH3vwbPyXfRtVmyxiT8o7J" +
                    "0qMGTfJeZT1S0xAUamdWDnKFoCBtVUYtHqaQJYBU1U9GGO0+hdt7Sv+24h86Djyhy1gRRun6jNImxA4i" +
                    "kkpilJKnSThWEmaiiXdoTpssJhNFJ0mxdGFeLFr/pQM2CJX6swEnNnp4bPP3IdnnbJ4QkvRrx1Yj9976" +
                    "EzsWuo4eikddJxeFs0zJ/5uuA4lAwVXaeWw1vGmJZgMjHGgdcc17nnvSFlrURSFcrS8HetNPIJRpUcVW" +
                    "2Cy/KquWuVVBOpgbV+TtpzyqMS6F0DKWgHOU6QkGTd211IOlmz/TMBbzzyM33rKQWzt9E9YgC5Zwr95e" +
                    "Af+as8W9FTIUigdEmPI3Hk1wjas4Ob+JgZZAlPliZNhWCYYVwMRTCvnRLGbpAdTqf7CmCgomFGWZain8" +
                    "h1QfNIPErWfThoLqt7ZZ0QEYkKJcoU26kDONBP5r3VRoSyS81IWQWJyrU8FR+ojJJRGLm+6ZfHPL5zDu" +
                    "86ZPaG9+gcWOvj4g2fgttn1emSCyFoDYqI5UwxBW8eK+BQ7r8LBQBmsfAs40DLFlpIhcbwsHYXlVb0DX" +
                    "HCkvCaz7p2ib4+acyqECkWVz6xnl7FLrVx54nRNUnJm5G4u1Mo1zlSwmpHXQ5SyVamtrh2IMX6KpLLi9" +
                    "ywuWFfi3z5rHy6aObG50Zv3bMTvP3gG5sqiKr1x6Xc+nBxUupJkwmCUI5F8DZgp3d/Gp+VX3jgbsHFcq" +
                    "L9cvirFN1N27I3XihXYAJjCyWIbi9p9m8nQ7c+FW210u1k2AUhm4vBKQ6ic9+dV7yYaGqTKcQbImAR6N" +
                    "hE4z+ZaH20C413nHcb7ds5iy3h5wgJ0f6+F/+fBbfjrJ6rmAIaortFY8yGyzixGj6QZ4CSfpVBOAiJwW" +
                    "QGohIWxBEs21ki519qSYYhhUcBQCcsFyNhYwGctYIxzmrz5EGKDrqrC0VyC/bGhHWXaFo0zow6PgPDPm" +
                    "qXLDlzrSqtsBpaIOIUfJAn+is4HgXDKWInfeuoc3nXOoRNa1ftT+frN+3HV6Xv10DEM6D5DEB0M85lr8" +
                    "tElLvB4v4OHliZx/+IUfrgwgUd7VZ/+kPZnXYMOx80a5mjFWgMYEyHpwAowSq4cLBmVssKgCDN5WQudS" +
                    "uOLEZMrUv0N7Xrq3iSQjnKpN6phRaSGxGbPiUIkObhEZ92VupKkF2/o4Y8u34+nzfTwZNg2tPp4zvpDx" +
                    "zbCxQX+x6Et+IsnduCB7hQYJYzz9kMAy3n8MC4MagnWiH761jEFBFhbVumEwmZlT+7biA1m3UStivMPl" +
                    "zXL6JSSrNGmrP1aPT5lnC5ZJu2dJ2mTSgKfVR+A9+ycwz/beQgb2vaElqJrvY2jxCvX7cLPTe/G/5zbg" +
                    "k8/djb2leOVJDUGKAmmgHOqCMZYl/BTOVSFG81jCgdIy+BClvNGRopFfVEwUxBNgVEU4rLoKZVEkuvkJ" +
                    "z6VSJrJlI9iUTqJOFqp1rtPjgE4d6rEBy+cxy9sP3wSZasJWCrxinW78NTOLK59/Dx8a+6UwBigtJXad" +
                    "lW/pvDCwcCyrUpTSlu1RieCLS1MEVJUwrhQFYVEfR7VsMwpYNlDeweM9gZqo9Djd9FNW2Jmvq07TJmGB" +
                    "E9ZV+ILz9mPX9h2eE3Hgj+Z97Na8/jYtrvxwnX7YUvraCMXi3e3tvT2pHXzt1gMbxb1Ty6PwLINHVEsJ" +
                    "03RxNxcHkH3DwcqN/1RTwhVvS5lzgnr2D0Ly5pTxy2YNBVgn7Wph//4/L3YOd0/Kf6O8tahEh/bdheeN" +
                    "3MA1mqwsks+staDy4Z+/NaW4bXWWvdeG8Fq3TE4x+ZwyPIfRFGZlf44TiebU9IkrZ5gOmARcJC0zMDlG" +
                    "5bwhSv2Y6O3R0/uR30nZnzotHtw8eShCnCoPH8W9czV9EWXh2Gtk5YcwBpMQ5+HIQj+wJmGCeQOxFgt1" +
                    "c85cHJK8jW/jeuUF6fSVlgCm9olPn35LDaN2ZOi7hhvM6aH92z5EYgZtvQSslLrlcSsJKuXoD665G1NG" +
                    "wDozARhGlhrg/T0ZkJABK9QonJKzmZBOXy2BWdFMaE2Q5GBTzxjDhdO909KuTXaLxnbjzdtejx2l/HS0" +
                    "qfjcQQhgkngTIGyDMANoGRWnKkv6OMR+k6NCFQeCkrOBAiGH4rUHFXZWeeyU/p49endk6Jtjbc3rX/EV" +
                    "QE4iRmcIjhpqp0pD1wrABo6oqCSvhBgta5FOoNXKdafo6cU+igZYiZqU/Pp+qppGUT7QoDx/gvmMUa8Z" +
                    "jwpZ2zvn8ZtWzGPp47P4e6F6XAtjUFMdjEG1pau6x9VMUMX1i2trRK2IbP7Ue//5Wql7Oo2oBjQ3Az1f" +
                    "qfRkyc1+E1PUte5iFvHGT+7aemYokPNOoUe0psLQf/0AJfxgqkncOd8B4UtUBZ+TI+FNYSCq56q7Kamk" +
                    "AXIxCZp1pUNeakqw8MyhZNDod8KYv2cIfTziSaoj71OAgI14SrB67KBtk2UmGrxMQWoHMJbJmPOOQHyT" +
                    "9u2s3UAZW8rrKnypCyVMFxUTWdMUeW2Whs6sBhbVhUWxqi6fTXOE7KERVOcqyBRm/OkZOpfmgZYz5uSr" +
                    "Xg8mCMEOgWOSccSCdC+mB/VTyb1Wc/rAiPFpJ9s24RdwBQvYLYchyl9g4sShgoYU4lJQ7FNpfFpfhTnA" +
                    "oSQT1IdEms7DQrdTvxIgMqZ9GjUuvRl1X7GqNUteKhGYRkcXdHlQeqB6IdILLkRPT2OwyXKZCYqMDTS9" +
                    "6TbLEpMYBH7ltzEFJeEQqbvugAWbixSHDEZxwAZVWaimgADoeu1AYGL1uokpdS7tiEz4aSh9smV3AbnS" +
                    "b4+R8Xy0QOpHLrbdeBcLIGFMv69ZIE9mMbDtAl7aRo9KrDXzLjUNX8KkgVIVK9jooYxX8lod/Udffmwb" +
                    "IYrukLL98nn6x9BNZtP/m2Mqb2fIKag+M8EcPqGDjaKkgvfccUYg1yiEom0ujDyRx1T/J4gkQ2+//BjZ" +
                    "lVUf67XabNloHv31yakKLDGx62low7SJVuBc7EEDveBw+72QNnGN825uK+1DYdoshl8DcBIwbfc+3XHl" +
                    "bOf2wTcHEhJdUPhxt/h7xsBVH+/TYSxZNHI+/74Tb/FuNorUm3Y9fA199gKVH+23WAUj4xYEy5zTHNSR" +
                    "zTKRJrk6jP+urz6EjUF6YID5nwfmOsDB/oFvkln4zvt89GjojZ7IAVE7qKkwEgfG+V+CrRU4slQpLzAg" +
                    "75rCkQdzsyoeifRjTGhiK9p8aR/17rcuL9jvRRnFxTzKjTy5ZyOTxBcAy8laj91nDjW/ETKopK/B5eqC" +
                    "XltWj2QciJJ5/vAXA841Ad+Uk7iy61n4SBNiia28aJJaTBIaqRAyKr1RKINerwJrPI9qs5+iFSWkiwHD" +
                    "vlZ8n3pZ6Tfq0mbDPtOHEwHfZ6btpEiU82Rg4bEVznaWrbE5kyglXU09bFFwr4ls3rS1Hntfp7pYQfS2" +
                    "T5wV7kJNxTPxUGarKnHYZJnmBRIJc2g+zlpOkg6pmD18fZB31k+nwNsbiGECFLDZzR93iCzwx/PA1Qui" +
                    "EGbGV0ysQ7Hp9kmtbnrDR1/OecwxQdn+4Rv7W+vSrza5+P23SieBQfSuR5wX38DbiouwyJatZOYnrSmi" +
                    "zJIeuaAkkpRFkkdTeBKbbpBgJUgGGUxSSDJ96WSVQJVgisFtDxObsHL98nXhXPOq5TmV6sd5AGxGiVJO" +
                    "VN3yDVw+3zFP3u4szpAtdUkPi9NF5xd+ljZwU2ty8CJPZo6BzlgNqnNpmPkgD3o/SnQ7IhNxPxn+ouev" +
                    "i/3O1M7tyzLmvTMScJhEnuQKZMCVz22Ovmoabkz1w+dStUMWOvVV2k7IMLfPdHCfXOtVZGo1lbSdLHvH" +
                    "SjCl4vLsEhjA734HIAGqb30dhQp2AR6qfpTWzDn2KXvaZLSTfapMUYBNgemnOTOAXJUjZM6V8PKUUbI8" +
                    "GcNzloL6gYt3gBWuXJUqaywB3oM/P4PJ2BX4P17T7/vCPyu8/Zvx3bsMTNZ9drk7IxqAuSkxDDnaxCIh" +
                    "0ltQes0fpccoHISUdJRg+xVdi19pOTNnZtRbP2alF0x4Z8mmaTFeqqnFLS3n/s7E7Vi6FqpGx8dw6XrJ" +
                    "vHes4+smM8nlvSlRC0NvtU6d6DjkrMpm0AjO9Ol1NEoDEHKXeY8bvm8lH7DPPY4Xa9O7HuADbOtBy1cY" +
                    "0xVy9/A4ebOQc7J0p+zwiZptR5SKkZPecLfk/y13lRVfJiTihVKpukyA797fwdPm+7jpZuWjgyotnKkf" +
                    "Jj0bmzBnJnIktGjXLgmSSNtQy/FhpH6XhK2Wq0aGOWxJKiLolB0We43eGkngVoURdZ5S+3hnH0tP0tK8" +
                    "FarFZ5vtVq1QMCghZ5bBDwk66c1qjBl1pwnxJBcn13QDOhEgrJvJiFHDyLEg/1vmO8Db//uNL58+SE8d" +
                    "0PviIBaerCWwN1ma3bEUBNpPkxNe3vwkksuwcc+9rFlL6b3v//9uOuuu5TaZWa88Y1vxNvf/vbwug984" +
                    "AO46667lIpOuU1rLSYmJnDNNdfg9NNPBwDccccd+NCHPhQ4y4985CO49NJLV0z53XHHHfjIRz6CsbGxX" +
                    "HRpqJkxzMRaJa8/4QBkZSFnPLcm71+apaKLdGL+42Cf8Pq/n8b/3De2bJLfwsX1GegxYZfZMJDXbCLiB" +
                    "0VxluOZp1u/30dZlkEK+u0v//IvsWvXrvD3+973PszPz2NhYQH9fj9LCZVliRe/+MUBpADw2c9+Fr1eL" +
                    "3wOr1JGjbUW3W4XvV4vHDe1VwfZ2zkHbOUtfZYT78/G/JMHa/aqjHDpjCr/mvnS4KrvTuGfnd3CB845v" +
                    "CyJarmSqrt5EovUHhjmHEWKpurYA01ut95669C8ACLCwYMHszQSEeHaa6/Fxz/+cQDAtm3b8MpXvhK33" +
                    "HJLUP/SS7fWYnx8HG9+85vDca6//nrcfffdmJyMwYz7778/S18xM2ZmZnDhhReGx2677bZGDve+++5T7" +
                    "/fNfVOzp4nRyDmvKw6hZowAAVaZ8pcAjlITIOdsicZTTKFzCtVa/TLm+gYfvb+Duw8VeM+Zi3jO+t7Qr" +
                    "8scnaq9mMzyeqPE6YfZqSnY3va2t6HVaqHdbqMoiqpDc/LZ/vnx8fFsDsEdd9yB22+/Hc9+9rMBAG996" +
                    "1vxla98Be12G2VZBsB6/vOd73wnpqenAQCzs7P4sz/7sxr1dP3112NpaQndbldJWWbGM5/5THzmM58Jv" +
                    "+Gd73wnxsbG0G630W63FSMgv/egPIRcTsMgE2tlPCoPYa0Ssr4xKpKlrUj3UXVzSvNcawXbv3p8DC+9f" +
                    "Qb/9J51uHOujTIfa1D5owygKyJQOcnYxIUOCn02OWDGmHAxJyYm0Ol0MDExofZOp4OxsTG0Wq3gPaeZS" +
                    "5/85CfDMXfs2IGrrroqqFwvFcuyxKZNm/CqV70qvPbaa6/F3Nwc2u02Wq1WWBT+dmJiApOTk5iamsLk5" +
                    "CQ6nQ7a7XbtN4yNjYXXTU1NYXp6GuvWrcPk5CTGx8eDI5ij5/x3S4MHUqqOmpByhPQUDXlZhFldsmZoq" +
                    "nQMtFhb+pV6Ese/f3QMNz42jqdO9fGUKYuf2dDHBZMltoxZGDB6FlgsCXMl42AP2GXawFidyskBbljqW" +
                    "hOA/VYUBcbGxgIYpURNo0IepGnSSLvdxhNPPIEbbrgBb3nLWwAA73jHO/CVr3wFS0tLKIoC7XYbzIx3v" +
                    "/vd4bO/+c1v4qabbsLExESQiNJc8EMjJKD6/X5wjPzmv//ExEQApfT+vZQeRJWlwkBKYK+FlJBY6bAJn" +
                    "TM6oHVvpijKj2nJcqzC6yfVVz3MkMvarJ7P6jPje4cK3D3Xwl89Xp1oE2bUxr5GzIwtW8Zxztk80DYah" +
                    "VfMmQ45ieolWQpUSUWlF1qqTQ/EG2+8Ea973eswMzODmZkZvPa1r8WNN94YpNmll16Kyy67LBzjU5/6V" +
                    "ACZB5j/fABKCsosJvka+RvGxsYwPj4eFkUKvFzCiwThoPS+pjTHFSalAGkaFDd0RhnerAJJtErOKvX9M" +
                    "knZLaS607pisXRspVsrfQZKSyi5aqduhakyyCPNhTUHqaZhzpKXPN5OlZIo5R1Te9ebD4uLi/iLv/iLc" +
                    "Ox3vOMd2LJlCxYXF9HtdvGmN70pPHfdddfh+9//Ptrtds2sSCmkoijCYsoR95K79a+R0jmXBD1qwkxj/" +
                    "gOvAlDroOMEmDwQm6HVoAqlosa5wk/54yhdWY49CQ9TlMZiAFOUvBR7CiubdbTEkpwUGJXzG4U5SOmen" +
                    "HfswfqlL30JjzzyCABgZmYGv/Irv4LFxUW87GUvw+WXXx4cqOuvvz7Yxh5UOedwFIANOle53Nuc9ExtV" +
                    "h+QaIrArWKTNK5zqcyqYC+LwFzSigSrTEgNs4vkBRWTN9KSQNEP2A/4ZslOhPF2XD8xAxJLhtmhw+L5M" +
                    "n3NU1gyRj4oVp5GrsbGxvCJT3wiPPemN70Jp556Kl772tcqB+rw4cMYGxsL5kZTuUou8SWXgD2IHx1Wk" +
                    "pNbjE35B+GaDBiHuiyvv7HhGeclbz6tmgYIac8EQINVVbD46SCkCwvFqEVSpgAp526QFGsi+ZfroZZli" +
                    "X6/j16vh6WlJbV3u10sLS3ViPhcQotUv3feeSduv/328Pg111wTeM/bbrsNN910UwB1qs7TJJG0imGYV" +
                    "M3xrsO0SPrZqXmTLtRhWSmjTZceNvqkaUoay7mcOc9fMqVJkUsqPZmiaUBp0gtijgBIjTD0zKwc4Z5Ts" +
                    "cOcp1FoLb99/vOfr5Hy6YW87777cN1116lYf1MhobcTP/nJT+ILX/gCAODpT396eN0f/MEfoNVqYXx8P" +
                    "ABVJqNIJ6cpiaQpuymXyJJWCOT+TkGaPufLT5SdPkCiLqOHP9VTVIZ0RpH+kp6Hqj3/mCsAUVZNtUzVO" +
                    "M1atl5HCBgQZ9guPziNm0n8pgvYBNgcxSW3K6+8coTIGaPX6w1Uu6kHvnv3btx88814wxveEJ774he/i" +
                    "HvuuQfr1q1TQYZBGVy5fNRhtrQEm6e4clWo6ffOCYYwsC2hqBqoTx5N9VM6Pq457j+odwRnWPk6O6BzX" +
                    "jmlW2UfgPDOiHDVZ4NJMbLDnIQmNqDJhhyWBzAKUPv9ftZebjIDjDHYvn27Os6rXvUqzMzMBMnbVOI9C" +
                    "v+7HL54kBROF0EuCpirySKMJlE5i62QNpWS+pSklKZqvD6Aom4+pAEAqo9HlyKb8h1ZPFgpPF83qgeVS" +
                    "aSe/rA8VZnplLtY55xzTpBu7Xa7dgxP9YyPj2eTlbPZ7wBe/epXh5Cq39avX4+rr74af/qnf5p1Ugb93" +
                    "lGTRmRINGfvNoVMc6aC1GAyN8C1q2wsljcj6Py8s9RAV2kilZspqlSyhnmTmkGILEEyHFUG86HHLbIAd" +
                    "grWUSoph2X/5HI1c5EpHy6dnJwMuw9H+rCldHoGeekTExO46qqrlMr329VXX43TTjsN/X4/OGhN37dJQ" +
                    "zRlSQ3SCPI4Ta/1i2dYuUs2Lp8BKg+O7nNDv9AGjx8DCv9SAkBOqEgXVG6sYpg/RWEwKjESioz0Cgst4" +
                    "3mgil0OWAepUBnR6XQ6CqiTk5Mq1p/G+XPHL8sSr3jFK7B169bg5X/4wx/G9773vfC6D37wgyEPQJoUO" +
                    "Smdk7yjqP5RarZSRyyVrjmwJve5Lg3BpiGwxC6gY3Wf02Hg4wxYCY09qYO3Tk12Rx2s8thOyjIFA8A9z" +
                    "qhN3MyUJg8i/nPqt0m1po951e7B6m/97mPwnkaScfRUGllrsXnzZvzSL/2SYhXa7Tb+8A//MDz2nOc8B" +
                    "y984QtVZlTOEWqquR8E3KaF3GRvDjIzchysOBZngZSo/hSkYU5GXpZq2A1eoDSA+Aea+v8PBiuLt6Z5V" +
                    "umCac6GSsszhqn1nBRtyqDy4VMJSE8dyX2Qc1OWJd785jdj3bp1AIAvfelL+Pa3v43x8XHccccd+Na3v" +
                    "hVe+xu/8RuBp/VmgPyOaRZ+kzRcbqg4pbBS3rWJvsosAquxFy+kyRieWqImWUzZQiweEO3n5vGUWbAmZ" +
                    "bM1sHIOrOzmprJyymoSuMFma7LfRilpHhS5GsU7Htap5JJLLsFrXvMaFc9vtVrodDrodDq45pprwnM7d" +
                    "uzAL//yL2NxcVFl34/6HXJE/yCwNjVaa5K4KZWVLhzb73UFUG0K1FxVvI07d30cvTnXhDPdUwbnpuZ9M" +
                    "WEGcIbGUiMJU7Ba4d1zHtQjAG4QgAdIgmWpzKbXpfafT4j225e+9CXs2rUrMAadTgd79+7Fn//5n6ukl" +
                    "fHxcWUCpLX4o4RCU2eoyfYctMhy5lKa0BKOaQx6SwsHmqRqMmi9KjMSt30Ah2oXCfUxkNIRryGaGhIO0" +
                    "mNwPEiYO0TUkGWQglVMMWbNriEzCnEYqEaxyZokZhrPL8tShUxlUnEaS/cA6Pf7ePnLX44LLrggJJ1ce" +
                    "+21IQLlqa/x8XF88YtfxOzsbEhaefe7360cq9xvznVDyXrbopHZqEV5Esi5itp0cRJVmW6HD+zd5XBXJ" +
                    "oBVql9K0r7be2z5ofgFTKONqkj/ho4Ug/qscRPfyk3gRC1IEGZrZh7HiNTMMAk7SiGftRa9Xq8W6+92u" +
                    "+h2u1hcXAyPeQ89zUOYnJzE1VdfHR773Oc+p5JOJE/b7XZxww03qKSVZzzjGVkWYDk5C4Mk5KBkmpzmy" +
                    "gFWshALC0s9a/vzDnc1qdrKALUU0rTH3L8VaL140BepNaVgQcyTzheoh0aRGbXijhneTsqu9UncXA2MS" +
                    "cAes7nYQrUS8lRPGi0ZZDfmbKthIdTrrruulnuakzo+3s/MIWfVX9RXvOIVwYGanZ3Fl7/8ZVVSIuP5P" +
                    "sH69a9/fYhcve1tb8P73ve+cFyf8jfsuw9yHIc11xjUG1aS+zmueN/BQ3sALAkhWUqwtqAmrCuV3wOwB" +
                    "Lt0J9DuAjzu9binPtPIVArCtJs0/JgW2WIcQ4JX0CO0U4CyGq+SSNmEbfCJGTIhYlBcu+n+sOyj5z3ve" +
                    "SODoNvt1uLimzdvxq/92q8pOmphYUEFCeT397kAf/zHf4yPfvSjAIDnPve5eN3rXodbbrkF/X4/mxw9r" +
                    "BPKIEAPagzXtOBzfKp/7OGfPPpVB9ReBqg11e+lac+9aQnAoi3x9ZRuEm3aE2jqCBWLmn9tl6bkfj6Z2" +
                    "r+WpSZgP25btGqLTQLE3zZIUmSaxzap+KbncjTWkSRUN6lEv7/3ve8Nr5mdncXNN9+ssvbT5hOet/361" +
                    "7+uUgF/8zd/E1NTU439Uwd1c5ELYliAo8m+H5bo418/3y3Lh3/wDzc3ANXKuCQBKAC0AYwDmAQwBWAGw" +
                    "AaQObNoTfwJiIumiFU6mkVF8NMLSdEkoBptRZrMoigViSnTbl0ci2Rag3XTYKolsXnTKThj+9bGNpNpP" +
                    "dOg16TOgs899bRQWjOUe69Xx957lxn53rbtdrvBVJHBgzRA4E0ab/cuLi4GNeuDDJ1OJ5tM7X+Df9/S0" +
                    "hKstWi324EC8+XSg2YF5CJrUgOl7dHlse6496G/vveOW68FcMA57/MAFgRwbSvRkTaRqF0Ai2C721r7n" +
                    "0xBr6lLVm4wAzgAtqbSVZmJwCdnUlrESuCMPUvS/rV+FUd5bRr4wjQXMj2hg9R+qva86vVh0abepGmSh" +
                    "w8CpCDwz3U6naAFUrs0zSP1ZSt+EZRlqRZEmmKX/ja/aHxPKb84/OLJ2Ze5BJWmBhMyNVC+Z+5wt/f97" +
                    "952nQNmV4CzZqPmnClvo3bdAdpcLl7PNHklEW9Mp59UNisn/amknQpR35Qw8A6AKn2P0vwrTeCTyOgKr" +
                    "7E+V9WK8TioFAXbGlCauM30RA4aAiFDprkMo1RFp8fygJQRKv+4r/qUVaI5uzFtmpZmMqXqO/fb0sXgn" +
                    "/PAHzaBZVBSTy5PQKr+b33nro8z834Aiw5vvRw91crQ8J6eWnLPu51btlz8QNHu/BGYx1DT5iZkR1HNF" +
                    "XK1VUTq2RwLFROyfbQJuqNKeJpUtpWXrL4KoBp5SLWElGHdUIY1n8hJSX+hm7o6NyV0SMmeC78OClemI" +
                    "JDHSlPuhnn5/v2pw9XUe3UULnVQpM5/nzvvffhv9vzk/v8O4HCi6r2NGj6wkHlMmQA96ee4yxbfN6b1I" +
                    "iB13eWFyYwTrN8kD2RoK2W+piofCrzxO6QlINXzkxMdzKybHjoPKmdPDpMUUpLJXYIrV7bcRF81zGBq9" +
                    "LJzgG6ixwaFQuXr09lQgxiCURK10+f/8YHH/v573/n67wKYE0DtZoDKAFLnKCvskswSu4+Zv21M60Ugt" +
                    "HNvI0qdnroz1QTK+uMprOtp1m7kHEgCNClJmZzoYP3MuqzkHMYJLmdrukijNFoYpafqkUq1psU36ncc1" +
                    "PUkF8lKbeJI5zG+c/f9f33PHbf+nnCcDjuQdgWPyjmJKhFAiUTNJKzYWbb9vyUztpMIpw8EZO6kNEpQa" +
                    "gYr1wYDhuMTFSG4QBmDghiYSIC6XKAt5/FhA9RGkeY5J+5IpvWNOiUwF79vMh9y5soo28G5xd43bv/ux" +
                    "35y/91fdJLUg3RRgLRMHakUqEDjzB11643cLtve19jynWRaFxBhQx6s6QqkwZJVTh3mphMqpGc4BmUXg" +
                    "D/E5MQEZtZN5RMiBqiyJjW53PlTowB6lDS7UdVuTsINMwGWI5mX85pDC0vlnfc+9Dff/sZ//+3Ds/vvF" +
                    "ureg7TRNh2m4skxO0bwq20AY45nnQDQEfsEqDjLFGM/DzLPJaL1glHISDppTPjgK9f0v4nTXhMTgPKZg" +
                    "6KakVRQlXHqKRuwbeuWoWrLUyi5FuSjAK6JNx0mlXMtfkZ5/3KBOyzkOWyBNjmHUc0Dfcs8v9Bd2rPvw" +
                    "KO7dj32N4899IP/7KTnotsXhKqXnn4/kznVCNQmsLYygPX7mNj98x1QsQmmtR06QbsWGhhqJlPTygqF/" +
                    "rn3qXcZQ1QovmjAzxeSmVPnL+ckZrRIziYngJjZINUZcrozEYNgQTT4JzUKgAEOam06aO436sgjcnNtI" +
                    "/0nDDKybPvzs3t+/ENmlpJySXDyXcGVLg2K7SNXhDwCWH3kykvXFLT+1tNZHtgmOcawzzy5nVhbziSUX" +
                    "Lzn43siiNQTar7JJq2p/tYIX8Ima1HmBPgvkgK0ENJ4EEhPgvbEBCYy/LvERpqFJ0FbDgEoj0pDYQifS" +
                    "gKIRbKbBpCmPO1JgD65QJvW2tkErGUCzDJ5LQaBdDmAoQbQmgE75YMGJ7cnsfrPAbbMmAY5CcqjABBHC" +
                    "FgkNuig/aQ0/emQqozGiuZ8zf5ygIcjBOwg8OIkQH9qAYsRQLmsepj/fwBeqxm7vBv/bwAAAABJRU5Er" +
                    "kJggg==\') 100% 5px no-repeat;\r\n      padding-right: 205px;\r\n    }\r\n\r\n    p {\r\n  " +
                    "    margin: 11px 0 22px;\r\n      overflow: hidden;\r\n    }\r\n\r\n    ins {\r\n      col" +
                    "or: #777;\r\n      text-decoration: none;\r\n    }\r\n\r\n    a img { border: 0; }\r\n\r\n  " +
                    "  @media screen and (max-width: 772px) {\r\n      body {\r\n        background: none" +
                    ";\r\n        margin-top: 0;\r\n        max-width: none;\r\n        padding-right: 0;\r\n" +
                    "      }\r\n    }\r\n\r\n\r\n    #logo {\r\n      display: inline-block;\r\n      height: 54p" +
                    "x;\r\n      width: 150px;\r\n    }\r\n  </style>\r\n\r\n  <style>\r\n    .customTable td, .s" +
                    "ettingsTable th, .settingsTable th:first-child, .settingsTable td:first-child { " +
                    "padding: 8px; }\r\n\r\n    .customTable tr:nth-child(2n) { background-color: #F1F1F1" +
                    "; }\r\n\r\n    .customTable tr { border-bottom: 1px solid #DDD; }\r\n\r\n    table {\r\n  " +
                    "    border-collapse: collapse;\r\n      border-spacing: 0px;\r\n    }\r\n\r\n    table, " +
                    "th, td {\r\n      border: medium none;\r\n      box-sizing: border-box;\r\n    }\r\n  </" +
                    "style>\r\n</head>\r\n<body>\r\n<ins>\r\n  <h2>MP2Extended</h2>\r\n</ins>\r\n<p><b>");
            
            #line 90 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\..\..\..\BasePages\Header.html"
            this.Write(this.ToStringHelper.ToStringWithCulture(headLine));
            
            #line default
            #line hidden
            this.Write("</b> <ins>");
            
            #line 90 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\..\..\..\BasePages\Header.html"
            this.Write(this.ToStringHelper.ToStringWithCulture(subHeadLine));
            
            #line default
            #line hidden
            this.Write("</ins>\r\n<p>");
            this.Write(@"

<script src=""/MPExtended/StreamingService/stream/GetHtmlResource/ShowSettingsJs.js""></script>

<style>
  label, input, select { display:block; }
  input, option { margin-bottom:12px; width: 100px; padding: .4em; }
  select {
    width: 100px;
  }
</style>

  <table class=""customTable"" style=""width: 100%"">
	  <tbody>
	  <tr>
		  <th>Name</th>
		  <th>Value</th>
      <th></th>
	  </tr>
	  ");
            
            #line 27 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
 foreach (var setting in _settings) {  
            
            #line default
            #line hidden
            this.Write("\t  <tr data-type=\"");
            
            #line 28 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(setting.Value.Type));
            
            #line default
            #line hidden
            this.Write("\" data-currentvalue=\"");
            
            #line 28 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(setting.Value.Value));
            
            #line default
            #line hidden
            this.Write("\" data-name=\"");
            
            #line 28 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(setting.Key));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t\t  <td>");
            
            #line 29 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(setting.Key));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t  <td id=\"value\">");
            
            #line 30 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(setting.Value.Value));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      <td><span class=\"ui-icon ui-icon-gear\"></span></td>\r\n\t  </tr>\r\n\t  ");
            
            #line 33 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\SettingsTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\t  </tbody>\r\n\t</table>\r\n\r\n<div id=\"dialogError\" title=\"Error\">\r\n  <p><span class=" +
                    "\"ui-icon ui-icon-alert\" style=\"float:left; margin:0 7px 20px 0;\"></span>Error ch" +
                    "anging Setting! Please check the logs.</p>\r\n</div>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class SettingsTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
