// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MediaPortal.Plugins.MP2Extended.ResourceAccess.DAS.html.Settings.Pages
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MediaPortal.Plugins.MP2Extended.Utils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class UsersTemplate : UsersTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("<!DOCTYPE html>\r\n<html lang=en>\r\n<head>\r\n    <meta charset=utf-8>\r\n    <meta name" +
                    "=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\r\n    <" +
                    "title> ");
            
            #line 6 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\..\..\..\BasePages\Header.html"
            this.Write(this.ToStringHelper.ToStringWithCulture(title));
            
            #line default
            #line hidden
            this.Write(" - MP2Extended </title>\r\n\r\n    <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/" +
                    "1.11.4/themes/smoothness/jquery-ui.css\">\r\n    <script src=\"//code.jquery.com/jqu" +
                    "ery-1.10.2.js\"></script>\r\n    <script src=\"//code.jquery.com/ui/1.11.4/jquery-ui" +
                    ".js\"></script>\r\n\r\n    <style>\r\n        * {\r\n            margin: 0;\r\n            " +
                    "padding: 0;\r\n        }\r\n\r\n        html, code {\r\n            font: 15px/22px aria" +
                    "l, sans-serif;\r\n        }\r\n\r\n        html {\r\n            background: #fff;\r\n    " +
                    "        color: #222;\r\n            padding: 15px;\r\n        }\r\n\r\n        body {\r\n " +
                    "           margin: 7% auto 0;\r\n            max-width: 600px;\r\n            min-he" +
                    "ight: 180px;\r\n            padding: 30px 0 15px;\r\n        }\r\n\r\n        * > body {" +
                    "\r\n            background: url(\'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKo" +
                    "AAACqCAYAAAA9dtSCAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2Z" +
                    "pbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoC" +
                    "MFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQ" +
                    "uQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB" +
                    "6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVop" +
                    "FAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOc" +
                    "qAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHgg/P9eM4Ors7" +
                    "ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgugdfeLZrIPQLUAoOnaV/N" +
                    "w+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7iJIEyXYFHBPjgwsz0TKUcz5IJhGL" +
                    "c5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKSKcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP" +
                    "2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8//UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/T" +
                    "BGCzABhzBBdzBC/xgNoRCJMTCQhBCCmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/p" +
                    "hCJ7BKLyBCQRByAgTYSHaiAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1x" +
                    "GupE7yAAygvyGvEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOg" +
                    "YBzPEbDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKggHCQ" +
                    "0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmxpFTSEtJG0m5" +
                    "SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+IoUspqShnlEOU05QZlmDJ" +
                    "BVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgXaPdpr+h0uhHdlR5Ol9BX0svpR+i" +
                    "X6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1QwNzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyo" +
                    "vVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnUlqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09" +
                    "DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx" +
                    "0TgnnKKeX836K3hTvKeIpG6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/" +
                    "OBZ3nU9lT3acKpxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGsww" +
                    "kBtsMzhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZLTep" +
                    "N7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnutrxuhVo5WaV" +
                    "YVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFnYhdnt8Wuw+6TvZN9un2" +
                    "N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPjthPLKcRpnVOb00dnF2e5c4PziIu" +
                    "JS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/uNu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+" +
                    "VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N" +
                    "/I/9k/3r/0QCngCUBZwOJgUGBWwL7+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355j" +
                    "Okc5pDoVQfujW0Adh5mGLw34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5" +
                    "qPNo3ujS6P8YuZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZ" +
                    "ATIhOOJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCepkLx" +
                    "MDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQrAVZLQq2Qqb" +
                    "oVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0dWOa9rGo5sjxxedsK4xU" +
                    "FK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWFfevc1+1dT1gvWd+1YfqGnRs+FYm" +
                    "KrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebeLZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5f" +
                    "NKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ27tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1Wb" +
                    "VZftJ+7P3P66Jqun4lvttXa1ObXHtxwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZz" +
                    "G4iNwRHnk6fcJ3/ceDTradox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl" +
                    "5SvNUyWna6YLTk2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7h" +
                    "Xmq86X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/XfFt1" +
                    "+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9DBY+Zj8uGDYb" +
                    "rnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl/erA6xmv28bCxh6+yXg" +
                    "zMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz/GMzLdsAAAAgY0hSTQAAeiUAAIC" +
                    "DAAD5/wAAgOkAAHUwAADqYAAAOpgAABdvkl/FRgAATEFJREFUeNrsvXmYXGd5J/p7v1PVXb2oJUuWbC3" +
                    "eLYPBCzZgiFlC2CGsgUx8E7bgZLgPJPDMk4chlwkwM9yE4DsQh0sgk4BzPXEGxoTYecgw45nMEgZswBN" +
                    "MbOwYbIxtsGVL1tbqVnd11fne+8f5lvf9zneqqtUttWR09BxVdS2nqs75fe/yezfCyjca4f6w953cTqy" +
                    "Nl/Ecj/i+VQdLDowk9tzfJ4H50wFcHvH+skFLR/DaFIwmuU0fz7335PbkBKm/tQKcNvn7iEBLywCpBJs" +
                    "HYeHu+70Qj1NmP6n6n5yqPwWhTfYy81gTaLNbaxlSNAWo3FvivkkAfBKoT36gpsArBUD93k/+TgE7EKy" +
                    "tEUGaSs2W2NvJ/SIjaemk+n/Sq30rbiUgew6k/eR+P5G2Ax2u1hBVLyWpBOiYA+WYuO//bonX5uzXk9u" +
                    "TD6gpSK0AZc/tS2739417nhIJmwVrawR17yVkW4B0HEDH3fpdgrYlAGsaWIGT25PL05f2qJeYS2LvAlh" +
                    "0tx5THripGVED6zCJKkEqAdoBMOF2/3eHTGtDa3LT89vt1iWGaH1RFOtAGCeqDkf+0A6m1ePVY9VdjV/" +
                    "/PBmjvnp4nPx/1S2pY2Y+i4z6BCZxUK6+xVVnHcILNs2Jw5C4IVB2mVH+FFL6LIHFV66/hbBoDX77njO" +
                    "YQCCqdhjDhgyoIPjHTTgHBsbAHZdAZPS5JXEc/+HM4TF/HJjwX/jOLN5L4pcYAhgEMpR8FrC4sPgEw5Q" +
                    "HZg9+//Ef3fu12ccf+qED6CKABbe33d9NmrYGVmoAqLctvd3ppeYEgMl0LyY3PW9iYvoNnZbdXlBJGkx" +
                    "UA14AmbuYJICmLitVJ0M+7o/B1akSODUawOInGUNgDtfIvY7BYs0yM8CMf33RHly1Y9+aian5soXnfeM" +
                    "ikDEoTAW8oihQFIVbtARjChABhSn0eSY48EWwShBRWMwNz7vzYIwJ59Q/nl5HL3yqc8v6WOI1T3Rb8z/" +
                    "ZO3fr/d/+2y/0Fg7tATAP4LDYPYh7wlyosQKtBrtUgnRMgHQKwLTbp4rx9RdPTq57z8RYuYmot8xLQnH" +
                    "NuNXOFGSOk5aoPR5AJaVccpI8KD34w+sDsD1IGWQM2PLyGeijuVFczWSM/l7utxERLFsUVESguHMRwSU" +
                    "PKSVsPBd+8YbzTBTOFxGDYCrJGR4jtTMDxphEk0Vgb+6UU5u3T7zs/Ne89sX3PXrglnu/8dXPJf4LZWg" +
                    "uafdCy/q4pd69BOk6ADMA1o9Nn/au9TNTH+60+5vSiyzVTk6a5n6Q/5qs1CyFC+BRy+qEyY/h+tX2x0t" +
                    "8QxJmA3M8N/njrAVOCYb8V+EAHiKqpJ0wgRisgBO+fjivnAWrf7w6LuJ5pnThs1vIdYEACKAn1zR97XS" +
                    "Li8vOXP/qF73hLX8yPr3hDIejaaeVO8K/yfo1ZgBP2hY26aQ76DpQsamzfvvvzEzgpQYlmDlc7BoZxpn" +
                    "HCIn6r5voQTLkrPdMYJYT+16pIHWCteQkCWYaZDweey/Fn1fSYlR99/DPUPjucWHLk63BykHlQAFSCos" +
                    "UrFEjSWnKCqw5IKfA3TpRnvqSV772M5vOuvBZTvBNOUE4LtijIr3SJqN0ikTtK6B21m35wFR76emcRVG" +
                    "Ot+XaiQhan+sSzBj9Q5n1Sfb/FEo5XQjxBJKhsIRIfW4ursJBDa7p7ixwEMH6hSvsaA7nRYCLrVDrUOe" +
                    "ITGVrGmOq3dmoXPfllGTNPQcki0L4Bd4M8KZAXgITZlq98SuvuPxfTZ+641wH1EkH1rEkeBSkqklAahK" +
                    "gdoQDNTU2tfkdE+3+04JKANekpHdymnCqT2ICViExWMlJbjQlwq3/TUKKExkpDGAtYK0Vh6mbEceHSNV" +
                    "A4AjdsBDdugqq25BB1PyJiSRs11TTcEShPifeDFDAg/IrcmaAtXlbNgXtVFEWVz7/ef+mNT65Saj/cUF" +
                    "vmlT1NxH7yokyY+ueMdExr1CSMQEjc7MNOpgFoFQYNiSHsZYClLMhSJkOlfp0Kp7ZUSrkLnIUp/5vOg4" +
                    "QGzHFStJbZwoE0ARzwL1aOoXCJArnwJ9BLxhRMQQKtE6rKRMiYWuICGxZmQhxR41N8fZ1KoU3dmjysp9" +
                    "99b9IgJqTqspGlU5Uzdsfn5j8p4bLmspk/8+fRJBS1/JkKXuSKPzQYU5WuC+kr/aEtQQJVoF73FoLa0t" +
                    "x8llJdOao0Y4Hz19YIgCxouYsO0CysECZKxBTNIUCdSeA4YEstUzKGFDw4Flpv8BlIzp4XuqmXr80A1J" +
                    "7NqWyzl5PF2/Yft4liZ3aGqb6ZZg0OFNFZ8Pzx4v+ZlbGYF2N12xLqgnEKBVTwZwwBdzkcbH0/nIOl1s" +
                    "Q1pkmgvOLUjaj9j3Y+XgyAbykt5FDEs6WtdaR93GReUfJS1FmK0whUhrL89RZc0BekhqINVi9wJHANMb" +
                    "zrEbZrVL4+McuvPRZ7xae/1gmqjmSRO20xzq/4FdpTsUrm1MtK7EkalKRs1ZEnT1gdUzyVyVLQLvDepA" +
                    "6sWTFxfPSn7024Kj2w9pac2cK4sukp819Z/kWJ2HZ2ki5Cds9cNJgvfBZn3Ftz0bASTNAMwLanq3MBqP" +
                    "MgDRQ40Erpeu2KT5j/Wln7cxI1EJK1CYbtQ1gjIqxzWOmf9qwgG8NaELUN79JqjAZyhTXiMWDcllkqC+" +
                    "pXsDS0ULlSQX1xzGYgEivSWmy5pLU2c3WWreYLKwHKVv1WyWdxcJZDOfFsqIRpTmgggREWbDWmATSlJ+" +
                    "X1HVaSyMkJ1UBoCDgrAsu+sVMnshQrz+YAMXY9AtJZWEl3GUCGBYkdTD2OXWCMj+E4woDUZIdQ3VAo26" +
                    "jKdrEmLhIKoNJRagCpWNZq9g1hurhEnjdxkdx0cxhFMTaLve/0/sBgWeVgRL9EziEpyn87tR2VY5WstA" +
                    "5+BOcCRr462tD6JYbqMUcEyAfO/WU6YsyjpTX8iGEShn13wLQLori6UAZwJlCTFNRnIRDUbM7lQrJUk6" +
                    "U2vvR6ZIupfTq0zizkJwhuULSVhypNfn/WVNLaKO/pkBd6DEWf7wH547vwbM3tNDtTOPhcj0eKDdg31K" +
                    "nZg5wJXarTBEYuXrjWXaAM8KpMkUMSquol5SyLOxaEvkVCbMCEZY2MtHIhV5Trz+3TY3RdMY+DRq/hXz" +
                    "tU8jeJ6KNKVGvEevsI6JEZXOdotIIF4eJqidFOQMwtXBWlNIkIjaJPx+9eeaKmnTSySZS5+L1C3j+hgM" +
                    "o5ubRPWzWnpoigC2wcLiPKXsAV0wewEvW/xjznQ34Xwe34d5D0+hzAbYWpQOYsQAMKw/bnxG/SFlmmHF" +
                    "1JsgUQcCwreg7eU5Nmi5GMtQcJbKT8xok3MDsCMFijEFZlugUVEyesuXUw/t378vlAbQaElIkYMfr2R7" +
                    "JfSn5JHEvVlJ8fYJSR8GQTjsJYCWdmeIkgIXKvArUl1BhlgOl4h0OJZCZ8fId83jx5r2w80s4cBg4ZKu" +
                    "LuabanytwmCorES0DFAZoo8RZxV5cvGMvumYCtx7ahq8+ejoWbJWUwlTZ4UwAwzjgWZEiycrJClKO9Xm" +
                    "CB6vL1LLMAawkNKMJ9qmJi8No7ViZBCYGK1RCkU4YIi4xPr1+4+H9u2VliJKoyGRQGRH9NjVDn4RDk3y" +
                    "gV7M+lUzSTgqIMjkkY3qHLKokpGpF/Nt/RiS0WXimJvKQHN8LEF5z5iG8cPNB7Bg7jIOHgYOgIyziPTq" +
                    "bceBsCaAWpnI6CgK2jC/g/1j3Q7zy9F34293b8J8f24LZXjukM1owjGMASJ4za0FFIc4hAlhlVpXkVqN" +
                    "MYZ3rKoISPg/WLxiTpnNykDAxwQYx6dQ/Nj65bh0aKphzaX4JYDkkcwagJWBVCQ7uOYDr9qi6r5VF3v6" +
                    "NnnlKgXkzwXIVPgSxU10G5LziSoX6ZGfG5ZsXcfVT9uEp0/NYWAIOLQhwHEch1CpX2okUCVTjJK17ftv" +
                    "4YVx97v147Y5d+NyPzsfXHtsQVDy7sCr7aBGopn08iIugaqha2GQ09SjMsiCAnJIzDbyq0qbSDBDArGE" +
                    "HnMucolT1N5kA+ayijBpJTVeYOvKqH6Jf718asoUETRJUhYHyPCmcc3KEuFvVjoaSKXzbpkv8X8/cjSs" +
                    "2z6PfZxzuai6YMit1TSWqU/2FqQPVg9U4IWUI2D4xj3910T/grjM34hP/+BT8+HAHQJWvihIAikraOmA" +
                    "ai1gVgEq9F4L/RGL9SIFjUm6UGqKIJg3HSGETeVvP/YoLkitXopznkO1ukkq81EBmGYuEplTiFxX0vcg" +
                    "K8gm4MlavAgMEHTVSUSQbVDzrIDPWjVm855IDuPFVD+OF2+YqusdJqZT35jSCtoZkf5GqexNBG0BKdS1" +
                    "wycw+fOqZ38EvnrUL1vqgRoxi1RLEBfVl0yy1DFhNSOLWAQJW9BNqQQAhMRsCRqiXZST4a420xFPVnwJ" +
                    "XZteDg5fOMv7swZZk8kSpGu3MLI0VPDYOtTxV1KnKRAcb589Xr37mlkX838/djfNmurAM9Mt4nNQAOt5" +
                    "KZEmAs7JTOYDWA9U0JPFsaHXx7nPvxdNnZnHNPTuxUFa2oCECG0fbmQKWXYY/x4iVZQ5KsEoFlG6Qswp" +
                    "kLoWgvOTJ8+FTCPM0Jn87f8FmMDZIyzRIUjRdt0EdryQvl5K+KlJNEdRpEkvkXG0ErA/fsgCx5eAU+HQ" +
                    "3MDDZsvjQFXvxhVf8BDs3dLPnwnIikUhmLK0xSJFX90r1C43gTQBKAjE/e+qj+LdX/D0umJkPgYIQkOE" +
                    "YqeLk5FhxvWSFQT0RKAlvM2qhb/k4JckrsebKaOug4TKMRBrW85spyS9NkC3pKVCSW6rVCQuvXUegjMi" +
                    "+pxBShLOpLLhy6P0OxpXbFvDln38Ev3rhvqDmcz9bahmT5AgfD3mp/jsVBihaGqSUUf1NX3lHZw4fv/S" +
                    "7eNW23SqK6EOtCqzOOTYyjOw9f5HJL6t6lQZMol+cybLS0SgNVgXYjMBsjbrKa664ilhES1vbsiJRRNT" +
                    "2aBuClQFP4KCWIi/AYJ9MLFcqxWX4Ty6Yw+8+dzdaJgKUdF5HsPGS2EFwSo4HkeodSyVFi+hEebBSg/e" +
                    "X/oT1rS5+a+f3ACLcsus0FJ6+crwrnIqPAokDV11xoA6O1lZGXSHMNi9gTN2HkUWZaS5AcL7ZZmuuctt" +
                    "woBI1uFOCaeV8Vo4Mu0kXnx2ImLwXb1RCi498EEXvPtD5nAQNAHzwOfvx60/bV49z+yQtkRXlwWs8uZ5" +
                    "qBMbaE/4ClAUBLarbp8bZjKN8VwPG+8+/Ey1zCb76yGkwpoC1jMJUzABZAybrXgm0HCVQlU6TAljZL1G" +
                    "0isDgRMFTXelsJEv8NgtOggIqPrkCoLIkGQX36Ul9GfFkfdUZDGICE9dyAqrAAETdvgiBiuNYmSCslh9" +
                    "jvMX49M/twcvPmBv49ZNob5BGhgaYL2tJTRmgVbhb70il1BQNlqy57b3n3IVxY3HTj7fCmMKRJhZsCLa" +
                    "0MEUVKKmiUaTpAde8I+QAiOYTIYnFaHZc92CI1CJT6svwCIttVH2U5IAqmkLCMBG8aV2VyrVSKaqVBy+" +
                    "Uu3DEfOqgDZ97SqePP3nJ7oEgRerRJ6s7reqm40T1e0qq1cCh1kA64iIriPHrZ92DF5y2F5YdXSWy29h" +
                    "G2xWB1opqWlbCRqqLM5qUaglyVqRSSjNguPs+KlBJZ3sQ0kzw5P/aZzdk4Td5j4IKkcklRIEjwETL4rM" +
                    "vfgIv2j4/mtVSz0yrg5O0s7CWXr93lIxp5lBrC2/ErU0Wv7PzDuxcdwilLV3OK4sUwpj26M9/WdqYFpk" +
                    "4WjL7X5KvUbaRcqg4YQNGRaoZaYlrvwi11HzFieaSOpIOJ0JiyvKWEDsWGU6Vwc4V7+ZO5Kdf9AR+5rT" +
                    "Dw8nzTPdNynCntd6Ya5zhLzlUH98vUpB6XpOFrTribsD48FPvxOkTXdiyHygrb9dbkSIY+k4JBkDSVfE" +
                    "aOu1qjEq8ToMDwRQgSsrcaZVUPyBq6nXjsKy05NSYTkKiolQyZK67bx5q0DikQwQH6xMv2IuXnjG/fH2" +
                    "atosVEpWIU8tmTbcYkeLg8RdUl6oriVKcPjaP3zzvBzDEYFtW4BTBFMsszAPU8n1JsD9p1zCuYSWNesl" +
                    "EbJ1TsDKg5kzetMEY6pniqWTljIjPSVltRHp6ivGWC+fx5vMPjaxC0yB+CkRl7x0nICXSkSlln4rvrCJ" +
                    "TRxisuGL9Lrz1rIdjmNXxq9ap+PgYaxuVWXRGqVcE5wNDHCnKJDo5Sl+FkW1UQs6Gowb3WtSP1/CaVpl" +
                    "GO1RGSmxVFxzU0kvOWMBHn7NneWrUChUp6ShHj8lQ5PEUQpXOVIu03UoATOqPrsDM+MXTf4CzpxaqOix" +
                    "blZQQ60YSCLkYLBLWdQOMPFilAKPQ2C2taWsMdS7PRo2EQ1DXooVh/DH6g0JZic6A0I3IVHkyi/p8q/j" +
                    "TdWMW/+LZ+1HQyqWVz+8liiaG9BmPB8maStJWoT1+0OotrDZZ/NZ5d6FDfXdJfBFhLIb0Ws5a2btBh6V" +
                    "lQwzJ4udZgTqbREPU2giqP+U/uMEMSEsfNfUUaulV1xNWCyD8eCuqQxl4/zNnsXP90pG50EmNSi586vM" +
                    "7VWxjjXbiCpitgnWan7BRiVZXDVwwuQ8vO30PGAxbCnrKWuiOS4LpUZ0GE4rSh72tiBISZR0q/7dM5j5" +
                    "y1Z9R3vpkJbYKQ5RMcwbglDQEi3HoioaqmH4G47wNPfzKBbMr43ugQ6VSCqS5nceF+qcoQYM0FY6Uyp5" +
                    "ape2Xtt6HDe2lYKf6lj1gq7rORPOM8/0cZMK0oqtEyTbHlpnaDODVcaa06K7bF+F7KeHa3EmFhdgLWTs" +
                    "WACwsgDYxPvrc/RgzvCIJFW4Rw6mG0t4Bx4lDJUKmMhIViohSkB4BPZXbT20dxhu3PhKui7clgx2KKEE" +
                    "lNSUb/KaZWECS0ES6EYny9HlVeFRSwGMV5yT1hUj0uifS6p5VFxDK2q4sukG/5MwuXrhtYdUiPlLlS4G" +
                    "bJlKvNeFfhPBpc2RqNe1Uv/3cxh9juuhFle2viI0pglYkkmr3wmo7U5SxWy81ZSYdUc0J5xXzqFlONuX" +
                    "VktAOCdszCVnWmvjIrmCC73zbhXOrHp+sFYWR3gUjtmY2akECpKIi1f99tHJnN7fn8ZqtuwKwVC6xCMq" +
                    "EzjI+qm+8Vw/VYUU51kmzC+XOODNvFWzUVEUmZbHQ3n4u8x+i3MTKX87Sf4npfi89o4sXbVtYNQAYAVT" +
                    "mujQyOpCyxl4/xcyppAKVsDqqvmn/+VMfxGRRBrI/ZuU7z1/Qh8w2BHGIqNbrVpL8IewqqjPUY0ne8hF" +
                    "KVE48eM4S9rV2L1nmVB+r9hnu5Pzq0+ZWRY2qW9KqX0pSpRmOA0eqRlGZY5OLsLk9j3Om50VDOQTC39u" +
                    "qtSuZpFbW/G/Z71UwABAt9XVL9yO1UTkvPVPBKWO+9RfkU+1jm5348Ppxi0tPXTq6eEjsPMLxMWyCED3" +
                    "9tMjvWK2hKzbsFT2ErTMFxLAP3zNApHFxYirUABxs2eg4R++bVXHhEat+lZaYGwJR+0KctRwo+UFSIkt" +
                    "6+Hlbl7BpvFxVleZYlphALb5btmBuDXcD5/n7BGpvp/LRVft+v3LmUbTIhq6CISJlpf8Tw6tBTHFGB6d" +
                    "CLs2WS0paVqT6qZZLCtHGsPkN9WhDfhKHbDYLZrz0zMWjI0EziytSfnxceP61OD8l3v4x2LaPz+KcqTl" +
                    "HP/mOfhwYgOgAc1JPx6qb4yDJmoQxoQuvj1D1j5I3mAPt0FqYTMFgqwCevXlpVevkUymUpvZBMABrbqO" +
                    "ylqQFiUb2x0qiM+PidQejQLIcyptjy/bYH5WFto3Ne1mZBkpAxfbYSRLLikKoOaTqUoM0NYm5Caz1Dn/" +
                    "xfvWDN45bnD5ZHlUsSOkUVKs5vjqltAqgbYB2Kxb0HcvtzMl5x5ly0hfPt0qyes5UIngis0JKA/vxTLI" +
                    "tE9vh13tkHpUzYFUpeZxp+ThAlMtMKRkImGwzxgtebSHVCFZP+Bs6Poh/QgVQX30qQ7zHctvY7iJOj2F" +
                    "RnkLKLrVWD8TTwQJ/jvX8hCq3IuHdh6jf1mgXWXQ5zhl7mb6mkDNNRQRAdZWWKTjuhWOmUnWr5nwLdU+" +
                    "sHaaQ3wl9fy0df2+CtPxuNPd7rLZTikUQi9FGuoVIqO41puJUW4UR3QChJGfFtxohWf3l93mYRvspR6r" +
                    "6eYgtmokIJBNIhJSldJ6JLlMpV3swSUMkh0gnpZhjTAENJPyLSuV7mmotTJJTigV0Wn0lkNjTJ4lN6Uu" +
                    "qVS8rq5NTfE/bOi5GNIeOSEhxgzstJ5MgP4hCl1SnVWqExT6hb4+Kj6K+pgyZyjS640X1tw3QLtauMca" +
                    "UWcJ00Y/TY0Au/bI+p0sLNHLjLElXfmRGzwfgujwBWk2gpqXMac1BzYej+ngekc4YcepAO7sEzHbN0Ym" +
                    "jQzduMIgcZctUOaBHszH6SCQFOYlaxOz+2vT6Y7C3qcR00UdoCBX+Cx3vYpFebARa6/DnzcU4PFl79xz" +
                    "6Q/BqS1TOOFWD5AM0dJPZMknPCsz2DO490D5qHGW6S9XvJdmqBhrE3lghm9BpnRZX0tTkMyqPifkBxmT" +
                    "LOikKFe6UlBRDJ654u1O2koz2J+Wd7WRy9hEBlTPzouJAsbyXL7uRKBuAkhaSHrMk6mpAuOXHnaMS7ZH" +
                    "3fSTKJ3745I9FO7Z60rOp9WHTvFf397ijptY6StYmG+cmiO8im0fUk0lk7b7r8S+calUUKOuwmAdKVXO" +
                    "kwpSo1rI36HlCXee7vm1KPBDnr+NXH5rAod7qKOGciSclqU/4aBfALjuFQ/326gBU5uCy5rcVHpLHegx" +
                    "Mtjnap2u9ZSbOhHo20WA5bYLHCT+u52VJ/jzpbrI6qp9Vdl6gGtKVhFzrHqoXehEgR1d6VD02X+Dbu8e" +
                    "PiqMigyOhGVkBdLmFT/1g44rtTwwpRrBc39VrCsbEWPT213LrWRNWkdKS0lxNBtoh11xCjG3XdCXUKNK" +
                    "VVaGiIboka2GUn8SiWaytNT2Tvagy/SBArr3kR//3DOaWVtmpgiiPZjd1y0Wm/urRjXhsoYCbf7M8+9O" +
                    "KPfOcteK26X0W6FnAjFm0i1jiTYKzPJZqv7QGh8pWTWfWS0ZISVNOwQvoiTVJIIgwWmOFZSWl5EKllEp" +
                    "QzgcaYhEXQkeU+jiCaLP+4/4W/ujumVWVpimp7is8/9ueDfjCAxMjOy5SvacDqb3UVCpdSM/Sip31fqA" +
                    "AOmORNss1eDlW2wK3MNtrR168DlnRdjRNWIorzA+zkPDR/gyP9ONGKpdmNFNQSrtn4ll1AzmdVJygw8T" +
                    "XfebuKdz6WGdVJKksgpNRqAfmJ/B7352JhWYDDPpB6j2ocbeXDPQFIPuswdlP7h8kYGwCGHPSlJfLIqz" +
                    "yvq8/iYPCXmdlOiWTwkW1qeyZymlln7JdqR5MWDE9xRqRcixkrm97+r8mNXL9vOWAiVgYuFgS3vE/NuL" +
                    "u/WOrIk0padl436EO3nXrlsoWa6DUVJJP4vh4YHo70woAWgfCnlPpfRuB27cVcHvudq4F8AQwMSaSY2h" +
                    "4g+GjKWGf6E+i9M1HbApOEmS9TIbSTe+MMbUez4rSkobrynnU3NmhrEqtVf9z7O4XvENht1IiYTWvVj1" +
                    "zsGfwa3+3EXfuO3LnKleBev9cB+//35uxtyttpNjhmm3FdYoB1GG3wt70961Q6X0L9Mpq77vbXh9YKoF" +
                    "uH1jqV3+XBuhNAMWkAynVQZo90cdge2KpE7L6ybU4jxIxMe9q+aXVTexhFXMFvBNmVSgWq9TNT3YRIuR" +
                    "laANnmLNBSKY4SIbC9T2C61QNqgZK/OhQC7/4X0/FzQ9OHXltv5BK39k3iXf83Wb8YH+hylBMJhiR2p5" +
                    "eUsr7fSE1PVCXPEAt0C0dSMVO48DERqAzCXRaFXeq+mBxppAPeVPgaKj+Hxxep3wThpxFC5X0FLShkKz" +
                    "1WQ3italdO0Lg3yxPebIesNY0bI3Si8yJ6CekDWONnxpN7msZAsG4v4GDSwb/59c34lf/12Y8OHdkXKd" +
                    "l4PP3nYJ/8t+24LGFIpT5pjVdqe2ZqncJUAlSD8puPwFmH1gogcU+sGSBmVOBjVuAsXbF34YoVBoQGcA" +
                    "FH01B2+UWvrn/FNW5waTturne51QNuEMGrMLYJdlaZ4QEi9Zy9CcPYhFI2JpOGjJIDdFiZtWz388CYHE" +
                    "SqqBATAUzHDsVEwj/6eEOvv3YFrz6rEX8/BkL+JnNC0PzV/d2W/iPj0zjpgcncfueMV1/njRGkJ56061" +
                    "NnCfvFNnEk2fnQFlUtxMd4PQtwOSkG1ImWkZSU2BlDbT/HfOn4fHuOExBYa4qxPBdRhQufmx6rc2XhZv" +
                    "dADXP1o94r/2YleajIok6+QkYWgJ5VS3+TixPGVJlkt4eEqOcY/2MMIhCyI4J+3oFbrhvEjfcN4nz1ls" +
                    "8e3MXl2zs4cypHiaKSmceXCrw4KEWvrNvHN/eM44nFo0egSidzjClxUlNWweoJOe99y7vl86W9d59X9B" +
                    "RfQY2zgDn7IhDPQ0AS7oX1hqF9Wvbf9m3PYBPXsdqbRs5GbUalFyI7iimiG1+kEjWxC/3I5Z4hNTO0SW" +
                    "qaHWSNski3TdYS+AaWPWI7Nhj0ydmC3xy5PDCGCCK4GYAD8y28MBsgf/wACXdWKBKZZQXLRK3SVwFf9d" +
                    "LQQ+gMic9c3STU/+SfgKAc7cDWzbl7S7G8dOXFQAO2XHcMbsuDkmTY1coApTIaBUu+44xqdJ5pnh9Q/M" +
                    "1hxarsMSrAVRkm/USSI02Vz3eJPWgDGj3PiKQYWGQQ3netR6snCyLIAlln3nUO04IY59Y/+3Vv1z50mG" +
                    "SUjO1T6Wd6qkoabfOTAA7dwAz083XoPHy8NoA+MtPnItDvcKN8nHmkfHnLtbFeMXqQejPP1tWBR9AMlP" +
                    "MTZTmPOu+MqAykihSEhIl9RCLnvvpmc8PsyZKzADEHkdkxFIlPbKSxGMgEaojCipKzlsNrzcmmCpaChA" +
                    "sGD2rwSrJeanqPQ/q6SgJ1q2nABefe+SJ2GsB0l39dbjxsW0ifxSho0l1iggFUWWbkp895askjTbRyPk" +
                    "ZLl3ACwM9ITyVrCsBKteJKjmJT5nRInTGYUwki+7TXO+a4iSn9YAPibaoSVZ2yjKqm9iziESVQLBFmYS" +
                    "36k6uJzrEOCAWLWdYePEepDKq1BdSs8+OK+XKy++7iY2XnAns2Dw6K5/pN7wm2427z8aiLVCIGK63Sxm" +
                    "EQlQ5S4fZuHp/MqTBCNFhBVKjep7LCo51NWzU2izynB0qwUpqEEJlejYUBroZ8Ma1J6TkuAq80uMRTc0" +
                    "IRk85AQFuoURnTJgNBNFHiSLP6g7d7WtbU9qfUoJ6oPYsoWeBjdOMy88D1k+uXl7Csdq+Prcdf/3YFph" +
                    "WbGQWNI/xPoFjSQoSPnVc8BQGLXOIMsakpCTdj6MNzDz8l7eWfeaYRaJznRSgAW+uPS/sV/YhN8uV3cM" +
                    "UbZwAWIpBJNahWN2XlWpOWxgf5CkTD9OUlLaMxTLamRKQfQHWpZIUh7pzC+NZ5x95R8C1HHF5sBzH539" +
                    "ydlDlRCY2LTO6zMTboaaIRXohN1XkAwb4+vE/ThRX0tmnjkE5ViuUqGK6JSUSPT5TA2ujN6uzG2qvk+2" +
                    "DTFDTFJseMikbmCgJcamkU2hmgqoZn2mFt9TRloGFXozReyB2Sy9dCUs2Rp3aBfCipzK2bcIJu/3+Ty7" +
                    "Gg4sTaky58UkHbhZuZedbEBXRTzZS1sSyE4JRs6TCeQ4nPZZR61GVK/b6ExSSTpaoBQKY6zmGDVOqa0S" +
                    "3e53hGocAmWYYKS2vqliVuoRJ1KLKldz0ZG9CxGHDbjFS1fjrsIssLQmp6tV7zz3et8CODYzn7QRmJtf" +
                    "YuFzB9rk9T8Nt+9fDEKEwRgRkKrAGHtU5qBCAUxpO+BMhjdMNxGJJ6xABthwUdT9SoBK0f1/j+2WYCU2" +
                    "zpwKwoAd5cfoJDngwUA6VZpuERA3qRk66phSjEeeezgrUSfUCnzNpS8b8kovPWwqSs2cjcAHgsu2MK3Y" +
                    "eXxzosp2nfefj3/34dBQtitOijQmq3/8NF0EkSUnBKOYxJkZTbD7BKR5kb4cqxMdAZr7fip0pbrQ5a8a" +
                    "1t2WZsqD2dmi9oEljXky5AkJ340iXM2KzLkltkaOajM56CYku3ixgMUPAx/TnelTF6oUE9YCdbAOvuYi" +
                    "xdeOJK0UB4OYDZ+P/ffAM19fKSU5vjyZteEAulArAkD/vXqJWt0bUPynGRwQYg1Mty1YQq0Ro5Tbq8sB" +
                    "KylbNAJIaqC5pHqiR6xSbc7GuKZCWbrCVXHzaIDmen/WZlEIwRT1UWmC+7yWqAKoFLtoiVP0JvN3wxE7" +
                    "88cPbK+rTE53GVM4Uycidu0ZGhJ8DJeVpQaOuRSVIWAiSeG2iDiwDeoNZMISkai1LoNbdq6wFoAh7kVC" +
                    "CXO8qKY3TIDyk7jZC5buwjU1NCygSOdIfrA7FFA/BSYM3yxyA6kFKAK48uwLpibwdtm186tEL8JXHTw1" +
                    "NyogQgGhAos8+B+CCLZgKIQxCIDVeQNn0zjJgrHBaOc5wCOahDfLD8nDttGzCX3GjVHd3tF+UDOclZxI" +
                    "ASXe3SFFR+FEc48lpxgBFnpQoJpiF76TKzI0u74UGa7SlnOovgfmec6ZKYH0HeMPFjO0nuKp/eGkaH3v" +
                    "oqfiHgxOoMEcVqyIGQBDJNpEIGqxyqqQ/lLwGMhMuWlqkMpFifwhJ1Mgu1oPOb2vZv1jRl6Qk53Kkcyp" +
                    "cZdAqhE4VnSVAHd11mWslLBMv813uHSqKRUtPrgSyUD1wo7+7vUqSXraV8bNPAdZ1TmxJ+rVDp+Ff3nc" +
                    "uFmwLxhgY5wjBeLC6ETyhuV3szy9zLQh6YVf9pdLmN7IilXXFXQByDGun1371gKqiEXq0YJ06GhTrjsa" +
                    "4TLNirjtwrKa86c+o9QQKBLQPGnjSTmRhhchePHH+h/TLCsAvOpfxgp2jh0GPT1XfwqcfOQ9f3rUJZCp" +
                    "vnFz3DQNTOUDegWJyHj6pAAmJPqa+nWTIm1D+ga3IfI6qPxiIzjeQF9h6wt/67n+rIVFF9Ej5U0Nz1KI" +
                    "HmDlcYu1m351EbdK4vv4i4X/vCJD3OgnELpuAYnI3c62bEjZPAT/3FMbZp57YUvT7izP43QfOxb2HJpw" +
                    "3H6NNpBLVK37UGO3txiJICn6GIaPs/WgeCLtThE1971QlTTN2pWz+uyKvX9mODT4/Z8n7VHcPAnaNP8j" +
                    "/rIRaUjD1ZS6ZHjSy+yARYFXRUbW95exDePvTF6oCwBOZetq7Hdf8cAd6HpwiEx8GTrIaUToiooGBQxU" +
                    "Ln0kknJBiZ7Qg8tkTJjajiMGo0AjCclT9rDyqVVP9WgJGLGZ0fDbNjxqENYdkWzlNQ1cNuMWChNoKq1X" +
                    "bVP5xK78x2WAGIN5g01iJD1+0H2/cduCElqL7++P4+MPn4L/uXu/CoARDJoCPqPobbmRlaMIlyp99Wl/" +
                    "l1fuEobrskMFHZi0ZvLmli/j0qNHSai9q1TL8eVBECjr6pO9rSoOgw20KeGlYTdiZJNCvknalES9fEwp" +
                    "zBDHtqCZLHJyoF25ZxL98+hM4f6p71KXo0czm/8ahzfjEj3bgoYWxEKsnXzFo9FCQUGSSJFkEK97lnHK" +
                    "QfNHmrwKAHCp2B9XncU2wRJMhuLPkZwKshkT1qE88v5h4kHiEJLP09fhgldySeELSxPDxUCU5Cfo1QWK" +
                    "ScKxk/TlH588dK7yEgV8//xA+fOHuYybxjgZISyb8f4+fhT96cEuMLjmAGkQVb0i191BglQnnzFXKpUx" +
                    "O94ClQhD3AciotXmyzK4QgGIAwM+rEpOqScwdi4GcIwRqmirY6MnXxeUgcgq6BJsEPZG0+0kkdnaIhvg" +
                    "oy2lVr/T+qzdtGrf45DOewIs3z53QtuhPlibxwR+ej+/NVg6TD2MaaA8+TH92lYRkjDiPMa+CJYft6/R" +
                    "ZlpCwqO23wiaNsZdgOlgCDCfD70i1eWLn/fv5t4MqUVtHorciNSQL/hpi9w2qvo7nTDWgUhoiugWdq6q" +
                    "bXDjPXpS+siuEYiK85LQF/Oun78XZk0s4kbe/2Xc6Pv3wNuzutqJU9Oqb1BTiWGvPHrT+WskZUJG+Y5H" +
                    "4LsPLnGQHVWMmY+MMFvVngAWsAZMViUVWg1UGZ9iu3OvPEkmikStRWtpHdWeJKEtH1er/kuCB9Dw93WR" +
                    "JsxBGJeBaWHacAMeW14YI7915EP/8gr0nNDfatQbXPnIO/sOuTcGbiQOIXVY+4rRm1ZBM5GVWgtQVVrr" +
                    "qisKH7HzI1NuoxLDWVjmqQlNB9kGligy1PorFDqzsJatxVJWmsLw0Bmilsf4o3rU3ECVg3YlCJPO9MwW" +
                    "REOIL6ZGXwOnHRBMByk72RWfWhWb9mjUkOnmAsbnD+Mzle3DlpsMntBS9e34aH/nRefjh4Y4eNEax3Xh" +
                    "4XPQ0Z3fxfMg0BDuEw1BNfa7OXaXVK97ZeCkpwCqlbLwWlFhhFCf1MWBD+R6pcCrb0UbgtI5A82M4VS8" +
                    "iSmJIlmi2oSRlrlVIOpzAetNbxJMr6VqR+WFFUpjSDQB41dYF/M6F+3D2ZO+Etkf//LHT8bld2zBbtqO" +
                    "zE5Kc5DB33c6Twa7bjHYPYgtNFqmT5BwhAkoLKkwcgueL91hnd8RkNqvf7z7IO1ZgnZMc/A1fPs2DQ1O" +
                    "t5SA0pahi1pNONAGnzlfdZGgY9Je8hoOzpXsxVUm3HqQsqwwsO48X+O0LZ/Eb5+0/oaXogX4LH3vwbPy" +
                    "XfRtVmyxiT8o7J0qMGTfJeZT1S0xAUamdWDnKFoCBtVUYtHqaQJYBU1U9GGO0+hdt7Sv+24h86Djyhy1" +
                    "gRRun6jNImxA4ikkpilJKnSThWEmaiiXdoTpssJhNFJ0mxdGFeLFr/pQM2CJX6swEnNnp4bPP3IdnnbJ" +
                    "4QkvRrx1Yj9976EzsWuo4eikddJxeFs0zJ/5uuA4lAwVXaeWw1vGmJZgMjHGgdcc17nnvSFlrURSFcrS" +
                    "8HetNPIJRpUcVW2Cy/KquWuVVBOpgbV+TtpzyqMS6F0DKWgHOU6QkGTd211IOlmz/TMBbzzyM33rKQWz" +
                    "t9E9YgC5Zwr95eAf+as8W9FTIUigdEmPI3Hk1wjas4Ob+JgZZAlPliZNhWCYYVwMRTCvnRLGbpAdTqf7" +
                    "CmCgomFGWZain8h1QfNIPErWfThoLqt7ZZ0QEYkKJcoU26kDONBP5r3VRoSyS81IWQWJyrU8FR+ojJJR" +
                    "GLm+6ZfHPL5zDu86ZPaG9+gcWOvj4g2fgttn1emSCyFoDYqI5UwxBW8eK+BQ7r8LBQBmsfAs40DLFlpI" +
                    "hcbwsHYXlVb0DXHCkvCaz7p2ib4+acyqECkWVz6xnl7FLrVx54nRNUnJm5G4u1Mo1zlSwmpHXQ5SyVam" +
                    "trh2IMX6KpLLi9ywuWFfi3z5rHy6aObG50Zv3bMTvP3gG5sqiKr1x6Xc+nBxUupJkwmCUI5F8DZgp3d/" +
                    "Gp+VX3jgbsHFcqL9cvirFN1N27I3XihXYAJjCyWIbi9p9m8nQ7c+FW210u1k2AUhm4vBKQ6ic9+dV7yY" +
                    "aGqTKcQbImAR6NhE4z+ZaH20C413nHcb7ds5iy3h5wgJ0f6+F/+fBbfjrJ6rmAIaortFY8yGyzixGj6Q" +
                    "Z4CSfpVBOAiJwWQGohIWxBEs21ki519qSYYhhUcBQCcsFyNhYwGctYIxzmrz5EGKDrqrC0VyC/bGhHWX" +
                    "aFo0zow6PgPDPmqXLDlzrSqtsBpaIOIUfJAn+is4HgXDKWInfeuoc3nXOoRNa1ftT+frN+3HV6Xv10DE" +
                    "M6D5DEB0M85lr8tElLvB4v4OHliZx/+IUfrgwgUd7VZ/+kPZnXYMOx80a5mjFWgMYEyHpwAowSq4cLBm" +
                    "VssKgCDN5WQudSuOLEZMrUv0N7Xrq3iSQjnKpN6phRaSGxGbPiUIkObhEZ92VupKkF2/o4Y8u34+nzfT" +
                    "wZNg2tPp4zvpDxzbCxQX+x6Et+IsnduCB7hQYJYzz9kMAy3n8MC4MagnWiH761jEFBFhbVumEwmZlT+7" +
                    "biA1m3UStivMPlzXL6JSSrNGmrP1aPT5lnC5ZJu2dJ2mTSgKfVR+A9+ycwz/beQgb2vaElqJrvY2jxCv" +
                    "X7cLPTe/G/5zbgk8/djb2leOVJDUGKAmmgHOqCMZYl/BTOVSFG81jCgdIy+BClvNGRopFfVEwUxBNgVE" +
                    "U4rLoKZVEkuvkJz6VSJrJlI9iUTqJOFqp1rtPjgE4d6rEBy+cxy9sP3wSZasJWCrxinW78NTOLK59/Dx" +
                    "8a+6UwBigtJXadlW/pvDCwcCyrUpTSlu1RieCLS1MEVJUwrhQFYVEfR7VsMwpYNlDeweM9gZqo9Djd9F" +
                    "NW2Jmvq07TJmGBE9ZV+ILz9mPX9h2eE3Hgj+Z97Na8/jYtrvxwnX7YUvraCMXi3e3tvT2pHXzt1gMbxb" +
                    "1Ty6PwLINHVEsJ03RxNxcHkH3DwcqN/1RTwhVvS5lzgnr2D0Ly5pTxy2YNBVgn7Wph//4/L3YOd0/Kf6" +
                    "O8tahEh/bdheeN3MA1mqwsks+staDy4Z+/NaW4bXWWvdeG8Fq3TE4x+ZwyPIfRFGZlf44TiebU9IkrZ5" +
                    "gOmARcJC0zMDlG5bwhSv2Y6O3R0/uR30nZnzotHtw8eShCnCoPH8W9czV9EWXh2Gtk5YcwBpMQ5+HIQj" +
                    "+wJmGCeQOxFgt1c85cHJK8jW/jeuUF6fSVlgCm9olPn35LDaN2ZOi7hhvM6aH92z5EYgZtvQSslLrlcS" +
                    "sJKuXoD665G1NGwDozARhGlhrg/T0ZkJABK9QonJKzmZBOXy2BWdFMaE2Q5GBTzxjDhdO909KuTXaLxn" +
                    "bjzdtejx2l/HS0qfjcQQhgkngTIGyDMANoGRWnKkv6OMR+k6NCFQeCkrOBAiGH4rUHFXZWeeyU/p49en" +
                    "dk6Jtjbc3rX/EVQE4iRmcIjhpqp0pD1wrABo6oqCSvhBgta5FOoNXKdafo6cU+igZYiZqU/Pp+qppGUT" +
                    "7QoDx/gvmMUa8ZjwpZ2zvn8ZtWzGPp47P4e6F6XAtjUFMdjEG1pau6x9VMUMX1i2trRK2IbP7Ue//5Wq" +
                    "l7Oo2oBjQ3Az1fqfRkyc1+E1PUte5iFvHGT+7aemYokPNOoUe0psLQf/0AJfxgqkncOd8B4UtUBZ+TI+" +
                    "FNYSCq56q7KamkAXIxCZp1pUNeakqw8MyhZNDod8KYv2cIfTziSaoj71OAgI14SrB67KBtk2UmGrxMQW" +
                    "oHMJbJmPOOQHyT9u2s3UAZW8rrKnypCyVMFxUTWdMUeW2Whs6sBhbVhUWxqi6fTXOE7KERVOcqyBRm/O" +
                    "kZOpfmgZYz5uSrXg8mCMEOgWOSccSCdC+mB/VTyb1Wc/rAiPFpJ9s24RdwBQvYLYchyl9g4sShgoYU4l" +
                    "JQ7FNpfFpfhTnAoSQT1IdEms7DQrdTvxIgMqZ9GjUuvRl1X7GqNUteKhGYRkcXdHlQeqB6IdILLkRPT2" +
                    "OwyXKZCYqMDTS96TbLEpMYBH7ltzEFJeEQqbvugAWbixSHDEZxwAZVWaimgADoeu1AYGL1uokpdS7tiE" +
                    "z4aSh9smV3AbnSb4+R8Xy0QOpHLrbdeBcLIGFMv69ZIE9mMbDtAl7aRo9KrDXzLjUNX8KkgVIVK9jooY" +
                    "xX8lod/UdffmwbIYrukLL98nn6x9BNZtP/m2Mqb2fIKag+M8EcPqGDjaKkgvfccUYg1yiEom0ujDyRx1" +
                    "T/J4gkQ2+//BjZlVUf67XabNloHv31yakKLDGx62low7SJVuBc7EEDveBw+72QNnGN825uK+1DYdoshl" +
                    "8DcBIwbfc+3XHlbOf2wTcHEhJdUPhxt/h7xsBVH+/TYSxZNHI+/74Tb/FuNorUm3Y9fA199gKVH+23WA" +
                    "Uj4xYEy5zTHNSRzTKRJrk6jP+urz6EjUF6YID5nwfmOsDB/oFvkln4zvt89GjojZ7IAVE7qKkwEgfG+V" +
                    "+CrRU4slQpLzAg75rCkQdzsyoeifRjTGhiK9p8aR/17rcuL9jvRRnFxTzKjTy5ZyOTxBcAy8laj91nDj" +
                    "W/ETKopK/B5eqCXltWj2QciJJ5/vAXA841Ad+Uk7iy61n4SBNiia28aJJaTBIaqRAyKr1RKINerwJrPI" +
                    "9qs5+iFSWkiwHDvlZ8n3pZ6Tfq0mbDPtOHEwHfZ6btpEiU82Rg4bEVznaWrbE5kyglXU09bFFwr4ls3r" +
                    "S1Hntfp7pYQfS2T5wV7kJNxTPxUGarKnHYZJnmBRIJc2g+zlpOkg6pmD18fZB31k+nwNsbiGECFLDZzR" +
                    "93iCzwx/PA1QuiEGbGV0ysQ7Hp9kmtbnrDR1/OecwxQdn+4Rv7W+vSrza5+P23SieBQfSuR5wX38Dbio" +
                    "uwyJatZOYnrSmizJIeuaAkkpRFkkdTeBKbbpBgJUgGGUxSSDJ96WSVQJVgisFtDxObsHL98nXhXPOq5T" +
                    "mV6sd5AGxGiVJOVN3yDVw+3zFP3u4szpAtdUkPi9NF5xd+ljZwU2ty8CJPZo6BzlgNqnNpmPkgD3o/Sn" +
                    "Q7IhNxPxn+ouevi/3O1M7tyzLmvTMScJhEnuQKZMCVz22Ovmoabkz1w+dStUMWOvVV2k7IMLfPdHCfXO" +
                    "tVZGo1lbSdLHvHSjCl4vLsEhjA734HIAGqb30dhQp2AR6qfpTWzDn2KXvaZLSTfapMUYBNgemnOTOAXJ" +
                    "UjZM6V8PKUUbI8GcNzloL6gYt3gBWuXJUqaywB3oM/P4PJ2BX4P17T7/vCPyu8/Zvx3bsMTNZ9drk7Ix" +
                    "qAuSkxDDnaxCIh0ltQes0fpccoHISUdJRg+xVdi19pOTNnZtRbP2alF0x4Z8mmaTFeqqnFLS3n/s7E7V" +
                    "i6FqpGx8dw6XrJvHes4+smM8nlvSlRC0NvtU6d6DjkrMpm0AjO9Ol1NEoDEHKXeY8bvm8lH7DPPY4Xa9" +
                    "O7HuADbOtBy1cY0xVy9/A4ebOQc7J0p+zwiZptR5SKkZPecLfk/y13lRVfJiTihVKpukyA797fwdPm+7" +
                    "jpZuWjgyotnKkfJj0bmzBnJnIktGjXLgmSSNtQy/FhpH6XhK2Wq0aGOWxJKiLolB0We43eGkngVoURdZ" +
                    "5S+3hnH0tP0tK8FarFZ5vtVq1QMCghZ5bBDwk66c1qjBl1pwnxJBcn13QDOhEgrJvJiFHDyLEg/1vmO8" +
                    "Db//uNL58+SE8d0PviIBaerCWwN1ma3bEUBNpPkxNe3vwkksuwcc+9rFlL6b3v//9uOuuu5TaZWa88Y1" +
                    "vxNvf/vbwug984AO46667lIpOuU1rLSYmJnDNNdfg9NNPBwDccccd+NCHPhQ4y4985CO49NJLV0z53XH" +
                    "HHfjIRz6CsbGxXHRpqJkxzMRaJa8/4QBkZSFnPLcm71+apaKLdGL+42Cf8Pq/n8b/3De2bJLfwsX1Geg" +
                    "xYZfZMJDXbCLiB0VxluOZp1u/30dZlkEK+u0v//IvsWvXrvD3+973PszPz2NhYQH9fj9LCZVliRe/+MU" +
                    "BpADw2c9+Fr1eL3wOr1JGjbUW3W4XvV4vHDe1VwfZ2zkHbOUtfZYT78/G/JMHa/aqjHDpjCr/mvnS4Kr" +
                    "vTuGfnd3CB845vCyJarmSqrt5EovUHhjmHEWKpurYA01ut95669C8ACLCwYMHszQSEeHaa6/Fxz/+cQD" +
                    "Atm3b8MpXvhK33HJLUP/SS7fWYnx8HG9+85vDca6//nrcfffdmJyMwYz7778/S18xM2ZmZnDhhReGx26" +
                    "77bZGDve+++5T7/fNfVOzp4nRyDmvKw6hZowAAVaZ8pcAjlITIOdsicZTTKFzCtVa/TLm+gYfvb+Duw8" +
                    "VeM+Zi3jO+t7Qr8scnaq9mMzyeqPE6YfZqSnY3va2t6HVaqHdbqMoiqpDc/LZ/vnx8fFsDsEdd9yB22+" +
                    "/Hc9+9rMBAG9961vxla98Be12G2VZBsB6/vOd73wnpqenAQCzs7P4sz/7sxr1dP3112NpaQndbldJWWb" +
                    "GM5/5THzmM58Jv+Gd73wnxsbG0G630W63FSMgv/egPIRcTsMgE2tlPCoPYa0Ssr4xKpKlrUj3UXVzSvN" +
                    "cawXbv3p8DC+9fQb/9J51uHOujTIfa1D5owygKyJQOcnYxIUOCn02OWDGmHAxJyYm0Ol0MDExofZOp4O" +
                    "xsTG0Wq3gPaeZS5/85CfDMXfs2IGrrroqqFwvFcuyxKZNm/CqV70qvPbaa6/F3Nwc2u02Wq1WWBT+dmJ" +
                    "iApOTk5iamsLk5CQ6nQ7a7XbtN4yNjYXXTU1NYXp6GuvWrcPk5CTGx8eDI5ij5/x3S4MHUqqOmpByhPQ" +
                    "UDXlZhFldsmZoqnQMtFhb+pV6Ese/f3QMNz42jqdO9fGUKYuf2dDHBZMltoxZGDB6FlgsCXMl42AP2GX" +
                    "awFidyskBbljqWhOA/VYUBcbGxgIYpURNo0IepGnSSLvdxhNPPIEbbrgBb3nLWwAA73jHO/CVr3wFS0t" +
                    "LKIoC7XYbzIx3v/vd4bO/+c1v4qabbsLExESQiNJc8EMjJKD6/X5wjPzmv//ExEQApfT+vZQeRJWlwkB" +
                    "KYK+FlJBY6bAJnTM6oHVvpijKj2nJcqzC6yfVVz3MkMvarJ7P6jPje4cK3D3Xwl89Xp1oE2bUxr5GzIw" +
                    "tW8Zxztk80DYahVfMmQ45ieolWQpUSUWlF1qqTQ/EG2+8Ea973eswMzODmZkZvPa1r8WNN94YpNmll16" +
                    "Kyy67LBzjU5/6VACZB5j/fABKCsosJvka+RvGxsYwPj4eFkUKvFzCiwThoPS+pjTHFSalAGkaFDd0Rhn" +
                    "erAJJtErOKvX9MknZLaS607pisXRspVsrfQZKSyi5aqduhakyyCPNhTUHqaZhzpKXPN5OlZIo5R1Te9e" +
                    "bD4uLi/iLv/iLcOx3vOMd2LJlCxYXF9HtdvGmN70pPHfdddfh+9//Ptrtds2sSCmkoijCYsoR95K79a+" +
                    "R0jmXBD1qwkxj/gOvAlDroOMEmDwQm6HVoAqlosa5wk/54yhdWY49CQ9TlMZiAFOUvBR7CiubdbTEkpw" +
                    "UGJXzG4U5SOmenHfswfqlL30JjzzyCABgZmYGv/Irv4LFxUW87GUvw+WXXx4cqOuvvz7Yxh5UOedwFIA" +
                    "NOle53Nuc9ExtVh+QaIrArWKTNK5zqcyqYC+LwFzSigSrTEgNs4vkBRWTN9KSQNEP2A/4ZslOhPF2XD8" +
                    "xAxJLhtmhw+L5Mn3NU1gyRj4oVp5GrsbGxvCJT3wiPPemN70Jp556Kl772tcqB+rw4cMYGxsL5kZTuUo" +
                    "u8SWXgD2IHx1WkpNbjE35B+GaDBiHuiyvv7HhGeclbz6tmgYIac8EQINVVbD46SCkCwvFqEVSpgAp526" +
                    "QFGsi+ZfroZZliX6/j16vh6WlJbV3u10sLS3ViPhcQotUv3feeSduv/328Pg111wTeM/bbrsNN910UwB" +
                    "1qs7TJJG0imGYVM3xrsO0SPrZqXmTLtRhWSmjTZceNvqkaUoay7mcOc9fMqVJkUsqPZmiaUBp0gtijgB" +
                    "IjTD0zKwc4Z5TscOcp1FoLb99/vOfr5Hy6YW87777cN1116lYf1MhobcTP/nJT+ILX/gCAODpT396eN0" +
                    "f/MEfoNVqYXx8PABVJqNIJ6cpiaQpuymXyJJWCOT+TkGaPufLT5SdPkCiLqOHP9VTVIZ0RpH+kp6Hqj3" +
                    "/mCsAUVZNtUzVOM1atl5HCBgQZ9guPziNm0n8pgvYBNgcxSW3K6+8coTIGaPX6w1Uu6kHvnv3btx8881" +
                    "4wxveEJ774he/iHvuuQfr1q1TQYZBGVy5fNRhtrQEm6e4clWo6ffOCYYwsC2hqBqoTx5N9VM6Pq457j+" +
                    "odwRnWPk6O6BzXjmlW2UfgPDOiHDVZ4NJMbLDnIQmNqDJhhyWBzAKUPv9ftZebjIDjDHYvn27Os6rXvU" +
                    "qzMzMBMnbVOI9Cv+7HL54kBROF0EuCpirySKMJlE5i62QNpWS+pSklKZqvD6Aom4+pAEAqo9HlyKb8h1" +
                    "ZPFgpPF83qgeVSaSe/rA8VZnplLtY55xzTpBu7Xa7dgxP9YyPj2eTlbPZ7wBe/epXh5Cq39avX4+rr74" +
                    "af/qnf5p1Ugb93lGTRmRINGfvNoVMc6aC1GAyN8C1q2wsljcj6Py8s9RAV2kilZspqlSyhnmTmkGILEE" +
                    "yHFUG86HHLbIAdgrWUSoph2X/5HI1c5EpHy6dnJwMuw9H+rCldHoGeekTExO46qqrlMr329VXX43TTjs" +
                    "N/X4/OGhN37dJQzRlSQ3SCPI4Ta/1i2dYuUs2Lp8BKg+O7nNDv9AGjx8DCv9SAkBOqEgXVG6sYpg/RWE" +
                    "wKjESioz0Cgst43mgil0OWAepUBnR6XQ6CqiTk5Mq1p/G+XPHL8sSr3jFK7B169bg5X/4wx/G9773vfC" +
                    "6D37wgyEPQJoUOSmdk7yjqP5RarZSRyyVrjmwJve5Lg3BpiGwxC6gY3Wf02Hg4wxYCY09qYO3Tk12Rx2" +
                    "s8thOyjIFA8A9zqhN3MyUJg8i/nPqt0m1po951e7B6m/97mPwnkaScfRUGllrsXnzZvzSL/2SYhXa7Tb" +
                    "+8A//MDz2nOc8By984QtVZlTOEWqquR8E3KaF3GRvDjIzchysOBZngZSo/hSkYU5GXpZq2A1eoDSA+Ae" +
                    "a+v8PBiuLt6Z5VumCac6GSsszhqn1nBRtyqDy4VMJSE8dyX2Qc1OWJd785jdj3bp1AIAvfelL+Pa3v43" +
                    "x8XHccccd+Na3vhVe+xu/8RuBp/VmgPyOaRZ+kzRcbqg4pbBS3rWJvsosAquxFy+kyRieWqImWUzZQiw" +
                    "eEO3n5vGUWbAmZbM1sHIOrOzmprJyymoSuMFma7LfRilpHhS5GsU7Htap5JJLLsFrXvMaFc9vtVrodDr" +
                    "odDq45pprwnM7duzAL//yL2NxcVFl34/6HXJE/yCwNjVaa5K4KZWVLhzb73UFUG0K1FxVvI07d30cvTn" +
                    "XhDPdUwbnpuZ9MWEGcIbGUiMJU7Ba4d1zHtQjAG4QgAdIgmWpzKbXpfafT4j225e+9CXs2rUrMAadTgd" +
                    "79+7Fn//5n6uklfHxcWUCpLX4o4RCU2eoyfYctMhy5lKa0BKOaQx6SwsHmqRqMmi9KjMSt30Ah2oXCfU" +
                    "xkNIRryGaGhIO0mNwPEiYO0TUkGWQglVMMWbNriEzCnEYqEaxyZokZhrPL8tShUxlUnEaS/cA6Pf7ePn" +
                    "LX44LLrggJJ1ce+21IQLlqa/x8XF88YtfxOzsbEhaefe7360cq9xvznVDyXrbopHZqEV5Esi5itp0cRJ" +
                    "VmW6HD+zd5XBXJoBVql9K0r7be2z5ofgFTKONqkj/ho4Ug/qscRPfyk3gRC1IEGZrZh7HiNTMMAk7SiG" +
                    "ftRa9Xq8W6+92u+h2u1hcXAyPeQ89zUOYnJzE1VdfHR773Oc+p5JOJE/b7XZxww03qKSVZzzjGVkWYDk" +
                    "5C4Mk5KBkmpzmygFWshALC0s9a/vzDnc1qdrKALUU0rTH3L8VaL140BepNaVgQcyTzheoh0aRGbXijhn" +
                    "eTsqu9UncXA2MScAes7nYQrUS8lRPGi0ZZDfmbKthIdTrrruulnuakzo+3s/MIWfVX9RXvOIVwYGanZ3" +
                    "Fl7/8ZVVSIuP5PsH69a9/fYhcve1tb8P73ve+cFyf8jfsuw9yHIc11xjUG1aS+zmueN/BQ3sALAkhWUq" +
                    "wtqAmrCuV3wOwBLt0J9DuAjzu9binPtPIVArCtJs0/JgW2WIcQ4JX0CO0U4CyGq+SSNmEbfCJGTIhYlB" +
                    "cu+n+sOyj5z3veSODoNvt1uLimzdvxq/92q8pOmphYUEFCeT397kAf/zHf4yPfvSjAIDnPve5eN3rXod" +
                    "bbrkF/X4/mxw9rBPKIEAPagzXtOBzfKp/7OGfPPpVB9ReBqg11e+lac+9aQnAoi3x9ZRuEm3aE2jqCBW" +
                    "Lmn9tl6bkfj6Z2r+WpSZgP25btGqLTQLE3zZIUmSaxzap+KbncjTWkSRUN6lEv7/3ve8Nr5mdncXNN9+" +
                    "ssvbT5hOet/3617+uUgF/8zd/E1NTU439Uwd1c5ELYliAo8m+H5bo418/3y3Lh3/wDzc3ANXKuCQBKAC" +
                    "0AYwDmAQwBWAGwAaQObNoTfwJiIumiFU6mkVF8NMLSdEkoBptRZrMoigViSnTbl0ci2Rag3XTYKolsXn" +
                    "TKThj+9bGNpNpPdOg16TOgs899bRQWjOUe69Xx957lxn53rbtdrvBVJHBgzRA4E0ab/cuLi4GNeuDDJ1" +
                    "OJ5tM7X+Df9/S0hKstWi324EC8+XSg2YF5CJrUgOl7dHlse6496G/vveOW68FcMA57/MAFgRwbSvRkTa" +
                    "RqF0Ai2C721r7n0xBr6lLVm4wAzgAtqbSVZmJwCdnUlrESuCMPUvS/rV+FUd5bRr4wjQXMj2hg9R+qva" +
                    "86vVh0abepGmShw8CpCDwz3U6naAFUrs0zSP1ZSt+EZRlqRZEmmKX/ja/aHxPKb84/OLJ2Ze5BJWmBhM" +
                    "yNVC+Z+5wt/f97952nQNmV4CzZqPmnClvo3bdAdpcLl7PNHklEW9Mp59UNisn/amknQpR35Qw8A6AKn2" +
                    "P0vwrTeCTyOgKr7E+V9WK8TioFAXbGlCauM30RA4aAiFDprkMo1RFp8fygJQRKv+4r/qUVaI5uzFtmpZ" +
                    "mMqXqO/fb0sXgn/PAHzaBZVBSTy5PQKr+b33nro8z834Aiw5vvRw91crQ8J6eWnLPu51btlz8QNHu/BG" +
                    "Yx1DT5iZkR1HNFXK1VUTq2RwLFROyfbQJuqNKeJpUtpWXrL4KoBp5SLWElGHdUIY1n8hJSX+hm7o6NyV" +
                    "0SMmeC78OClemIJDHSlPuhnn5/v2pw9XUe3UULnVQpM5/nzvvffhv9vzk/v8O4HCi6r2NGj6wkHlMmQA" +
                    "96ee4yxbfN6b1IiB13eWFyYwTrN8kD2RoK2W+piofCrzxO6QlINXzkxMdzKybHjoPKmdPDpMUUpLJXYI" +
                    "rV7bcRF81zGBq9LJzgG6ixwaFQuXr09lQgxiCURK10+f/8YHH/v573/n67wKYE0DtZoDKAFLnKCvsksw" +
                    "Su4+Zv21M60UgtHNvI0qdnroz1QTK+uMprOtp1m7kHEgCNClJmZzoYP3MuqzkHMYJLmdrukijNFoYpaf" +
                    "qkUq1psU36ncc1PUkF8lKbeJI5zG+c/f9f33PHbf+nnCcDjuQdgWPyjmJKhFAiUTNJKzYWbb9vyUztpM" +
                    "Ipw8EZO6kNEpQagYr1wYDhuMTFSG4QBmDghiYSIC6XKAt5/FhA9RGkeY5J+5IpvWNOiUwF79vMh9y5so" +
                    "o28G5xd43bv/ux35y/91fdJLUg3RRgLRMHakUqEDjzB11643cLtve19jynWRaFxBhQx6s6QqkwZJVTh3" +
                    "mphMqpGc4BmUXgD/E5MQEZtZN5RMiBqiyJjW53PlTowB6lDS7UdVuTsINMwGWI5mX85pDC0vlnfc+9Df" +
                    "f/sZ//+3Ds/vvFureg7TRNh2m4skxO0bwq20AY45nnQDQEfsEqDjLFGM/DzLPJaL1glHISDppTPjgK9f" +
                    "0v4nTXhMTgPKZg6KakVRQlXHqKRuwbeuWoWrLUyi5FuSjAK6JNx0mlXMtfkZ5/3KBOyzkOWyBNjmHUc0" +
                    "Dfcs8v9Bd2rPvwKO7dj32N4899IP/7KTnotsXhKqXnn4/kznVCNQmsLYygPX7mNj98x1QsQmmtR06Qbs" +
                    "WGhhqJlPTygqF/rn3qXcZQ1QovmjAzxeSmVPnL+ckZrRIziYngJjZINUZcrozEYNgQTT4JzUKgAEOam0" +
                    "6aO436sgjcnNtI/0nDDKybPvzs3t+/ENmlpJySXDyXcGVLg2K7SNXhDwCWH3kykvXFLT+1tNZHtgmOca" +
                    "wzzy5nVhbziSUXLzn43siiNQTar7JJq2p/tYIX8Ima1HmBPgvkgK0ENJ4EEhPgvbEBCYy/LvERpqFJ0F" +
                    "bDgEoj0pDYQifSgKIRbKbBpCmPO1JgD65QJvW2tkErGUCzDJ5LQaBdDmAoQbQmgE75YMGJ7cnsfrPAbb" +
                    "MmAY5CcqjABBHCFgkNuig/aQ0/emQqozGiuZ8zf5ygIcjBOwg8OIkQH9qAYsRQLmsepj/fwBeqxm7vBv" +
                    "/bwAAAABJRU5ErkJggg==\') 100% 5px no-repeat;\r\n            padding-right: 205px;\r\n" +
                    "        }\r\n\r\n        p {\r\n            margin: 11px 0 22px;\r\n            overflow" +
                    ": hidden;\r\n        }\r\n\r\n        ins {\r\n            color: #777;\r\n            tex" +
                    "t-decoration: none;\r\n        }\r\n\r\n        a img {\r\n            border: 0;\r\n     " +
                    "   }\r\n\r\n        @media screen and (max-width: 772px) {\r\n            body {\r\n    " +
                    "            background: none;\r\n                margin-top: 0;\r\n                m" +
                    "ax-width: none;\r\n                padding-right: 0;\r\n            }\r\n        }\r\n\r\n" +
                    "\r\n        #logo {\r\n            display: inline-block;\r\n            height: 54px;" +
                    "\r\n            width: 150px;\r\n        }\r\n    </style>\r\n\r\n    <style>\r\n        .cu" +
                    "stomTable td, .settingsTable th, .settingsTable th:first-child, .settingsTable t" +
                    "d:first-child {\r\n            padding: 8px;\r\n        }\r\n\r\n        .customTable tr" +
                    ":nth-child(2n) {\r\n            background-color: #F1F1F1;\r\n        }\r\n\r\n        ." +
                    "customTable tr {\r\n            border-bottom: 1px solid #DDD;\r\n        }\r\n\r\n     " +
                    "   table {\r\n            border-collapse: collapse;\r\n            border-spacing: " +
                    "0px;\r\n        }\r\n\r\n        table, th, td {\r\n            border: medium none;\r\n  " +
                    "          box-sizing: border-box;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n   " +
                    " <ins><h2>MP2Extended</h2></ins>\r\n    <p><b>");
            
            #line 97 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\..\..\..\BasePages\Header.html"
            this.Write(this.ToStringHelper.ToStringWithCulture(headLine));
            
            #line default
            #line hidden
            this.Write("</b> <ins>");
            
            #line 97 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\..\..\..\BasePages\Header.html"
            this.Write(this.ToStringHelper.ToStringWithCulture(subHeadLine));
            
            #line default
            #line hidden
            this.Write("</ins>\r\n    <p>\r\n");
            this.Write("\r\n\r\n<style>\r\n    label, input, select { display:block; }\r\n    input.text, option " +
                    "{ margin-bottom:12px; width:95%; padding: .4em; }\r\n    fieldset { padding:0; bor" +
                    "der:0; margin-top:25px; }\r\n    .ui-dialog .ui-state-error { padding: .3em; }\r\n  " +
                    "  .validateTips { border: 1px solid transparent; padding: 0.3em; }\r\n    select {" +
                    "\r\n      width: 200px;\r\n    }\r\n</style>\r\n\r\n<script>\r\n  $(function() {\r\n    var di" +
                    "alog, form,\r\n \r\n    name = $( \"#name\" ),\r\n    type = $( \"#type\" ),\r\n    password" +
                    " = $( \"#password\" ),\r\n    allFields = $( [] ).add( name ).add( type ).add( passw" +
                    "ord ),\r\n    tips = $( \".validateTips\" );\r\n\r\n \r\n    function updateTips( t ) {\r\n " +
                    "     tips\r\n        .text( t )\r\n        .addClass( \"ui-state-highlight\" );\r\n     " +
                    " setTimeout(function() {\r\n        tips.removeClass( \"ui-state-highlight\", 1500 )" +
                    ";\r\n      }, 500 );\r\n    }\r\n \r\n    function checkLength( o, n, min, max ) {\r\n    " +
                    "  if ( o.val().length > max || o.val().length < min ) {\r\n        o.addClass( \"ui" +
                    "-state-error\" );\r\n        updateTips( \"Length of \" + n + \" must be between \" +\r\n" +
                    "          min + \" and \" + max + \".\" );\r\n        return false;\r\n      } else {\r\n " +
                    "       return true;\r\n      }\r\n    }\r\n \r\n    function checkRegexp( o, regexp, n )" +
                    " {\r\n      if ( !( regexp.test( o.val() ) ) ) {\r\n        o.addClass( \"ui-state-er" +
                    "ror\" );\r\n        updateTips( n );\r\n        return false;\r\n      } else {\r\n      " +
                    "  return true;\r\n      }\r\n    }\r\n \r\n    function addUser() {\r\n      var valid = t" +
                    "rue;\r\n      allFields.removeClass( \"ui-state-error\" );\r\n \r\n      valid = valid &" +
                    "& checkLength( name, \"username\", 3, 16 );\r\n      valid = valid && checkLength( p" +
                    "assword, \"password\", 5, 16 );\r\n \r\n      valid = valid && checkRegexp( name, /^[a" +
                    "-z]([0-9a-z_])+$/i, \"Username may consist of a-z, 0-9, underscores and must begi" +
                    "n with a letter.\" );\r\n \r\n      if ( valid ) {\r\n        // add User to the DB, se" +
                    "nding the PW in plain text is not very secure, but this is not a high security a" +
                    "pplication\r\n        // it is intended for home use. If you use it in a more publ" +
                    "ic enviroment be careful!\r\n\t      var url = \'/MPExtended/DebugAccessService/json" +
                    "/CreateUser?username=\' + name.val() + \'&password=\' + password.val() + \'&type=\' +" +
                    " type.val();\r\n\t      $.getJSON(url, function(data) {\r\n\t\t      if (data.Result ==" +
                    " true) {\r\n\t\t\t      $( \"#users tbody\" ).append( \"<tr>\" +\r\n\t\t\t      \"<td>\" + name." +
                    "val() + \"</td>\" +\r\n\t\t\t      \"<td>\" + type.val() + \"</td>\" +\r\n            \"<td><s" +
                    "pan class=\\\"ui-icon ui-icon-trash\\\"></span></td>\" + \r\n\t\t\t      \"</tr>\" );\r\n\r\n\t\t\t" +
                    "      dialog.dialog( \"close\" );\r\n\t\t      }else {\r\n\t\t\t      valid = false;\r\n\t\t\t  " +
                    "    updateTips( \'An error occurred! Please check the logs for more details.\' );\r" +
                    "\n\t\t      }\r\n\t      });\r\n      }\r\n      return valid;\r\n    }\r\n \r\n    dialog = $( " +
                    "\"#dialog-form\" ).dialog({\r\n      autoOpen: false,\r\n      height: 450,\r\n      wid" +
                    "th: 500,\r\n      modal: true,\r\n      buttons: {\r\n        \"Create an account\": add" +
                    "User,\r\n        Cancel: function() {\r\n          dialog.dialog( \"close\" );\r\n      " +
                    "  }\r\n      },\r\n      close: function() {\r\n        form[ 0 ].reset();\r\n        al" +
                    "lFields.removeClass( \"ui-state-error\" );\r\n      }\r\n    });\r\n \r\n    form = dialog" +
                    ".find( \"form\" ).on( \"submit\", function( event ) {\r\n      event.preventDefault();" +
                    "\r\n      addUser();\r\n    });\r\n \r\n    $( \"#create-user\" ).button().on( \"click\", fu" +
                    "nction() {\r\n      dialog.dialog( \"open\" );\r\n    });\r\n\r\n    // Delete User action" +
                    "\r\n\r\n    dialogDeleteUser = $(\"#dialogDeleteUserError\").dialog({\r\n      autoOpen:" +
                    " false,\r\n      resizable: false,\r\n      height: 250,\r\n      modal: true,\r\n      " +
                    "buttons: {\r\n          \"Ok\" : function () {\r\n              $(this).dialog(\"close\"" +
                    ");\r\n          }\r\n      }\r\n    });\r\n\r\n    $( \".ui-icon-trash\" ).button().on( \"cli" +
                    "ck\", function() {\r\n      var effectOptions = {};\r\n      var currentRow = $(this)" +
                    ".closest(\"tr\");\r\n      var url = \'/MPExtended/DebugAccessService/json/DeleteUser" +
                    "?id=\' + currentRow.data(\"id\");\r\n\t    $.getJSON(url, function(data) {\r\n        if" +
                    " (data.Result == true) {\r\n          // remove the row from the table with a nice" +
                    " effect\r\n          currentRow.children(\"td\").each(function() {\r\n            $(th" +
                    "is).wrapInner(\"<div />\").children(\"div\").slideUp(function() {\r\n              cur" +
                    "rentRow.remove();\r\n            })\r\n          });\r\n        }else {\r\n          dia" +
                    "logDeleteUser.dialog( \"open\" ).parent().addClass(\"ui-state-error\");\r\n        }\r\n" +
                    "      });\r\n    });\r\n\r\n    // create the select menu for the user types\r\n    type" +
                    ".selectmenu();\r\n  });\r\n</script>\r\n\r\n<table id=\"users\" class=\"customTable\" style=" +
                    "\"width: 100%\">\r\n\t<tbody>\r\n\t<tr>\r\n\t\t<th>Name</th>\r\n\t\t<th>Type</th>\r\n    <th>Actio" +
                    "n</th>\r\n\t</tr>\r\n\t");
            
            #line 163 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
 foreach (var user in MP2Extended.Users.Users) {  
            
            #line default
            #line hidden
            this.Write("\t<tr data-id=\"");
            
            #line 164 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(user.Id));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t\t<td>");
            
            #line 165 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(user.Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t<td>");
            
            #line 166 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(user.Type));
            
            #line default
            #line hidden
            this.Write("</td>\r\n    <td><span class=\"ui-icon ui-icon-trash\"></span></td>\r\n\t</tr>\r\n\t");
            
            #line 169 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write(@"	</tbody>
</table>

<div id=""dialog-form"" title=""Create new user"">
  <p class=""validateTips"">All form fields are required.</p>
 
  <form>
    <fieldset>
      <label for=""name"">Name</label>
      <input type=""text"" name=""name"" id=""name"" value=""JaneSmith"" class=""text ui-widget-content ui-corner-all"">
      <label for=""password"">Password</label>
      <input type=""password"" name=""password"" id=""password"" value=""xxxxxxx"" class=""text ui-widget-content ui-corner-all"">
	    <label for=""type"">Type</label>
	    <select name=""type"" id=""type"">
		  ");
            
            #line 184 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
 foreach (var type in _types) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t  <option value=\"");
            
            #line 185 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 185 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type));
            
            #line default
            #line hidden
            this.Write("</option>\r\n\t\t  ");
            
            #line 186 "M:\Programmieren\C#\MediaPortal 2\MediaPortal\Incubator\MP2Extended\ResourceAccess\DAS\html\Settings\Pages\UsersTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write(@"	    </select>
 
      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type=""submit"" tabindex=""-1"" style=""position:absolute; top:-1000px"">
    </fieldset>
  </form>
</div>
<br>
<button id=""create-user"">Create new user</button>

<div id=""dialogDeleteUserError"" title=""Error"">
  <p><span class=""ui-icon ui-icon-alert"" style=""float:left; margin:0 7px 20px 0;""></span>Error deleting User! Please check the logs.</p>
</div>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class UsersTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
