-- This script migrates AudioItem aspect data from database version 2.1 to version 2.*. DO NOT MODIFY!

INSERT INTO M_AUDIOITEM(MEDIA_ITEM_ID,TRACKNAME,ALBUM,ISCOMPILATION,DURATION,LYRICS,ISCD,TRACK,NUMTRACKS,ENCODING,CONTENTGROUP,BITRATE,CHANNELS,SAMPLERATE,DISCID,NUMDISCS,TOTALRATING,RATINGCOUNT) SELECT MEDIA_ITEM_ID,TRACKNAME,ALBUM,ISCOMPILATION,DURATION,LYRICS,ISCD,TRACK,NUMTRACKS,ENCODING,'' CONTENTGROUP,BITRATE,CHANNELS,SAMPLERATE,DISCID,NUMDISCS,TOTALRATING,RATINGCOUNT FROM M_AUDIOITEM%SUFFIX%;

INSERT INTO V_AUDIOITEM_ALBUMARTISTS SELECT * FROM V_AUDIOITEM_ALBUMARTISTS%SUFFIX% WHERE VALUE_ID IN (SELECT MAX(VALUE_ID) FROM V_AUDIOITEM_ALBUMARTISTS%SUFFIX% GROUP BY VALUE HAVING COUNT(*) > 0);
INSERT INTO V_AUDIOITEM_ARTISTS SELECT * FROM V_AUDIOITEM_ARTISTS%SUFFIX% WHERE VALUE_ID IN (SELECT MAX(VALUE_ID) FROM V_AUDIOITEM_ARTISTS%SUFFIX% GROUP BY VALUE HAVING COUNT(*) > 0);
INSERT INTO V_AUDIOITEM_COMPOSERS SELECT * FROM V_AUDIOITEM_COMPOSERS%SUFFIX% WHERE VALUE_ID IN (SELECT MAX(VALUE_ID) FROM V_AUDIOITEM_COMPOSERS%SUFFIX% GROUP BY VALUE HAVING COUNT(*) > 0);

INSERT INTO NM_AUDIOITEM_ALBUMARTISTS(MEDIA_ITEM_ID,VALUE_ID,VALUE_ORDER) SELECT NM.MEDIA_ITEM_ID, MAX(V2.VALUE_ID) VALUE_ID, 0 VALUE_ORDER FROM NM_AUDIOITEM_ALBUMARTISTS%SUFFIX% NM INNER JOIN V_AUDIOITEM_ALBUMARTISTS%SUFFIX% V ON V.VALUE_ID = NM.VALUE_ID INNER JOIN V_AUDIOITEM_ALBUMARTISTS%SUFFIX% V2 ON V2.VALUE = V.VALUE GROUP BY NM.MEDIA_ITEM_ID, V.VALUE;
INSERT INTO NM_AUDIOITEM_ARTISTS(MEDIA_ITEM_ID,VALUE_ID,VALUE_ORDER) SELECT NM.MEDIA_ITEM_ID, MAX(V2.VALUE_ID) VALUE_ID, 0 VALUE_ORDER FROM NM_AUDIOITEM_ARTISTS%SUFFIX% NM INNER JOIN V_AUDIOITEM_ARTISTS%SUFFIX% V ON V.VALUE_ID = NM.VALUE_ID INNER JOIN V_AUDIOITEM_ARTISTS%SUFFIX% V2 ON V2.VALUE = V.VALUE GROUP BY NM.MEDIA_ITEM_ID, V.VALUE;
INSERT INTO NM_AUDIOITEM_COMPOSERS(MEDIA_ITEM_ID,VALUE_ID,VALUE_ORDER) SELECT NM.MEDIA_ITEM_ID, MAX(V2.VALUE_ID) VALUE_ID, 0 VALUE_ORDER FROM NM_AUDIOITEM_COMPOSERS%SUFFIX% NM INNER JOIN V_AUDIOITEM_COMPOSERS%SUFFIX% V ON V.VALUE_ID = NM.VALUE_ID INNER JOIN V_AUDIOITEM_COMPOSERS%SUFFIX% V2 ON V2.VALUE = V.VALUE GROUP BY NM.MEDIA_ITEM_ID, V.VALUE;

