-- This script is the default for migrating aspect data from database version 2.1 to version 2.*. DO NOT MODIFY!

INSERT INTO %ASPECT_TABLE% SELECT * FROM %ASPECT_TABLE%%SUFFIX%;
INSERT INTO %ASPECT_V_TABLE% SELECT * FROM %ASPECT_V_TABLE%%SUFFIX% WHERE VALUE_ID IN (SELECT MAX(VALUE_ID) FROM %ASPECT_V_TABLE%%SUFFIX% GROUP BY VALUE HAVING COUNT(*) > 0);
INSERT INTO %ASPECT_NM_TABLE%(MEDIA_ITEM_ID,VALUE_ID,VALUE_ORDER) SELECT NM.MEDIA_ITEM_ID, MAX(V2.VALUE_ID) VALUE_ID, 0 VALUE_ORDER FROM %ASPECT_NM_TABLE%%SUFFIX% NM INNER JOIN %ASPECT_V_TABLE%%SUFFIX% V ON V.VALUE_ID = NM.VALUE_ID INNER JOIN %ASPECT_V_TABLE%%SUFFIX% V2 ON V2.VALUE = V.VALUE GROUP BY NM.MEDIA_ITEM_ID, V.VALUE;

