-- This script updates the MediaLibrary schema from version 1.1 to version 1.2. DO NOT MODIFY!


-- Contains pending media item operations
CREATE TABLE MEDIA_ITEM_PENDING_OPERATIONS (
  MEDIA_ITEM_ID %GUID% NOT NULL,
  OPERATION_TYPE %INTEGER% NOT NULL,
  
  CONSTRAINT MI_PENDING_OPERATIONS_PK PRIMARY KEY (MEDIA_ITEM_ID, OPERATION_TYPE),
  CONSTRAINT MI_FK FOREIGN KEY (MEDIA_ITEM_ID) REFERENCES MEDIA_ITEMS (MEDIA_ITEM_ID) ON DELETE CASCADE
);

