-- This script migrates MediaLibrary schema data from database version 2.* to version 2.*. DO NOT MODIFY!

INSERT INTO MEDIA_ITEMS SELECT * FROM MEDIA_ITEMS%SUFFIX%;
INSERT INTO PLAYLISTS SELECT * FROM PLAYLISTS%SUFFIX%;
INSERT INTO PLAYLIST_CONTENTS SELECT * FROM PLAYLIST_CONTENTS%SUFFIX%;
INSERT INTO SHARES SELECT * FROM SHARES%SUFFIX%;
INSERT INTO SHARES_CATEGORIES SELECT * FROM SHARES_CATEGORIES%SUFFIX%;

