-- This script migrates MediaItem aspect data from database version 2.1 to version 2.*. DO NOT MODIFY!

INSERT INTO M_MEDIAITEM(MEDIA_ITEM_ID,TITLE,SORTTITLE,RECORDINGTIME,RATING,COMMENT,PLAYCOUNT,LASTPLAYED,ISVIRTUAL,ISSTUB) SELECT MEDIA_ITEM_ID,TITLE,SORTTITLE,RECORDINGTIME,RATING,COMMENT,PLAYCOUNT,LASTPLAYED,ISVIRTUAL,0 ISSTUB FROM M_MEDIAITEM%SUFFIX%;

