-- This script updates the MediaLibrary schema from version 1.1 to version 1.2. DO NOT MODIFY!

DROP TABLE IF EXISTS M_AUDIOITEM;
DROP TABLE IF EXISTS M_DIRECTORY;
DROP TABLE IF EXISTS M_IMAGEITEM;
DROP TABLE IF EXISTS M_IMPORTEDITEM;
DROP TABLE IF EXISTS M_MEDIAITEM;
DROP TABLE IF EXISTS M_MOVIEITEM;
DROP TABLE IF EXISTS M_PROVIDERRESOURCE;
DROP TABLE IF EXISTS M_SERIESITEM;
DROP TABLE IF EXISTS M_THUMBNAILLARGE;
DROP TABLE IF EXISTS M_VIDEOITEM;
DROP TABLE IF EXISTS NM_ACTORS;
DROP TABLE IF EXISTS NM_ALBUMARTISTS;
DROP TABLE IF EXISTS NM_ARTISTS;
DROP TABLE IF EXISTS NM_AUDIOLANGUAGES;
DROP TABLE IF EXISTS NM_COMPOSERS;
DROP TABLE IF EXISTS NM_DIRECTORS;
DROP TABLE IF EXISTS NM_DVDEPISODE;
DROP TABLE IF EXISTS NM_EPISODE;
DROP TABLE IF EXISTS NM_GENRES;
DROP TABLE IF EXISTS NM_GENRES_0;
DROP TABLE IF EXISTS NM_WRITERS;
DROP TABLE IF EXISTS V_ACTORS;
DROP TABLE IF EXISTS V_ALBUMARTISTS;
DROP TABLE IF EXISTS V_ARTISTS;
DROP TABLE IF EXISTS V_AUDIOLANGUAGES;
DROP TABLE IF EXISTS V_COMPOSERS;
DROP TABLE IF EXISTS V_DIRECTORS;
DROP TABLE IF EXISTS V_DVDEPISODE;
DROP TABLE IF EXISTS V_EPISODE;
DROP TABLE IF EXISTS V_GENRES;
DROP TABLE IF EXISTS V_GENRES_0;
DROP TABLE IF EXISTS V_WRITERS;

DELETE FROM MEDIA_ITEMS;
DELETE FROM MIA_NAME_ALIASES;
DELETE FROM MIA_TYPES;
DELETE FROM PLAYLIST_CONTENTS;