-- This script migrates ProviderResource aspect data from database version 2.1 to version 2.*. DO NOT MODIFY!

INSERT INTO M_PROVIDERRESOURCE(MEDIA_ITEM_ID,SYSTEM_ID,RESOURCEINDEX,TYPE,MIMETYPE,SIZE,PATH,PARENTDIRECTORY) SELECT MEDIA_ITEM_ID,SYSTEM_ID,RESOURCEINDEX,0 TYPE,MIMETYPE,SIZE,PATH,PARENTDIRECTORY FROM M_PROVIDERRESOURCE%SUFFIX% WHERE ISPRIMARY=1;
INSERT INTO M_PROVIDERRESOURCE(MEDIA_ITEM_ID,SYSTEM_ID,RESOURCEINDEX,TYPE,MIMETYPE,SIZE,PATH,PARENTDIRECTORY) SELECT MEDIA_ITEM_ID,SYSTEM_ID,RESOURCEINDEX,1 TYPE,MIMETYPE,SIZE,PATH,PARENTDIRECTORY FROM M_PROVIDERRESOURCE%SUFFIX% WHERE ISPRIMARY=0;
UPDATE M_PROVIDERRESOURCE SET TYPE=2 WHERE MEDIA_ITEM_ID IN (SELECT MEDIA_ITEM_ID FROM M_PROVIDERRESOURCE WHERE PATH LIKE '{00000000-0000-0000-0000-000000000000}%');
