-- This script migrates Relationship aspect data from database version 2.1 to version 2.*. DO NOT MODIFY!

INSERT INTO M_RELATIONSHIP(MEDIA_ITEM_ID,ROLE,LINKEDROLE,LINKEDID,ISPLAYABLE,RELATIONSHIPINDEX) SELECT MEDIA_ITEM_ID,ROLE,LINKEDROLE,LINKEDID,0 ISPLAYABLE,RELATIONSHIPINDEX FROM M_RELATIONSHIP%SUFFIX%;
UPDATE M_RELATIONSHIP SET ISPLAYABLE=1 WHERE MEDIA_ITEM_ID IN (SELECT MEDIA_ITEM_ID FROM M_MOVIEITEM UNION SELECT MEDIA_ITEM_ID FROM M_EPISODEITEM UNION SELECT MEDIA_ITEM_ID FROM M_AUDIOITEM)

