-- This script migrates UserProfileDataManagement schema data from database version 2.1 to version 2.*. DO NOT MODIFY!

INSERT INTO USER_PROFILES(PROFILE_ID,NAME,PROFILE_TYPE) SELECT PROFILE_ID,NAME,0 PROFILE_TYPE FROM USER_PROFILES%SUFFIX% WHERE NAME NOT IN (SELECT NAME FROM USER_PROFILES);
INSERT INTO USER_MEDIA_ITEM_DATA SELECT * FROM USER_MEDIA_ITEM_DATA%SUFFIX% WHERE PROFILE_ID IN (SELECT PROFILE_ID FROM USER_PROFILES);
INSERT INTO USER_ADDITIONAL_DATA(PROFILE_ID,DATA_KEY,DATA_NO,ADDITIONAL_DATA) SELECT PROFILE_ID,DATA_KEY,0 DATA_NO,ADDITIONAL_DATA FROM USER_ADDITIONAL_DATA%SUFFIX% WHERE PROFILE_ID IN (SELECT PROFILE_ID FROM USER_PROFILES);
INSERT INTO USER_PLAYLIST_DATA SELECT * FROM USER_PLAYLIST_DATA%SUFFIX% WHERE PROFILE_ID IN (SELECT PROFILE_ID FROM USER_PROFILES);

-- Create and copy data to new Admin user
INSERT INTO USER_PROFILES(PROFILE_ID,NAME,PROFILE_TYPE) VALUES (%MIGRATION_USER%,'Administrator',1);
INSERT INTO USER_MEDIA_ITEM_DATA(PROFILE_ID,MEDIA_ITEM_ID,DATA_KEY,MEDIA_ITEM_DATA) SELECT %MIGRATION_USER%,UMIA.MEDIA_ITEM_ID,UMIA.DATA_KEY,MAX(UMIA.MEDIA_ITEM_DATA) FROM USER_MEDIA_ITEM_DATA UMIA GROUP BY UMIA.MEDIA_ITEM_ID,UMIA.DATA_KEY;
INSERT INTO USER_ADDITIONAL_DATA(PROFILE_ID,DATA_KEY,DATA_NO,ADDITIONAL_DATA) SELECT %MIGRATION_USER%,UAD.DATA_KEY,0,MAX(UAD.ADDITIONAL_DATA) FROM USER_ADDITIONAL_DATA UAD GROUP BY UAD.DATA_KEY;

