-- This script migrates UserProfileDataManagement schema data from database version 2.* to version 2.*. DO NOT MODIFY!

INSERT INTO USER_PROFILES SELECT * FROM USER_PROFILES%SUFFIX%;
INSERT INTO USER_MEDIA_ITEM_DATA SELECT * FROM USER_MEDIA_ITEM_DATA%SUFFIX%;
INSERT INTO USER_ADDITIONAL_DATA SELECT * FROM USER_ADDITIONAL_DATA%SUFFIX%;
INSERT INTO USER_PLAYLIST_DATA SELECT * FROM USER_PLAYLIST_DATA%SUFFIX%;

