-- This script updates the UserProfileDataManagement schema from version 1.0 to version 1.1. DO NOT MODIFY!

ALTER TABLE USER_PROFILES ADD PROFILE_TYPE %SMALLINT% DEFAULT 0 NOT NULL;
ALTER TABLE USER_PROFILES ADD PASSWORD %STRING(250)%;
ALTER TABLE USER_PROFILES ADD IMAGE %BINARY%;
ALTER TABLE USER_PROFILES ADD LAST_LOGIN %TIMESTAMP%;

DROP TABLE USER_ADDITIONAL_DATA;
CREATE TABLE USER_ADDITIONAL_DATA (
  PROFILE_ID %GUID% NOT NULL,
  DATA_KEY %STRING(250)% NOT NULL,
  DATA_NO %INTEGER% DEFAULT 0 NOT NULL,
  ADDITIONAL_DATA %STRING(2000)% NOT NULL,

  CONSTRAINT USER_ADDITIONAL_DATA_PK PRIMARY KEY (PROFILE_ID, DATA_KEY, DATA_NO),
  CONSTRAINT USER_ADDITIONAL_DATA_USER_PROFILE_FK FOREIGN KEY (PROFILE_ID) REFERENCES USER_PROFILES (PROFILE_ID) ON DELETE CASCADE
);


