-- This script migrates VideoStreamItem aspect data from database version 2.1 to version 2.*. DO NOT MODIFY!

INSERT INTO M_VIDEOSTREAMITEM SELECT * FROM M_VIDEOSTREAMITEM%SUFFIX%;
UPDATE M_VIDEOSTREAMITEM SET PARTSETNUM=-1 WHERE MEDIA_ITEM_ID NOT IN 
(
SELECT MEDIA_ITEM_ID FROM M_VIDEOSTREAMITEM WHERE PARTNUM >= 0
UNION
SELECT MEDIA_ITEM_ID FROM M_PROVIDERRESOURCE WHERE TYPE IN (0,3) GROUP BY MEDIA_ITEM_ID HAVING COUNT(*) > 1
);

